### ISSUE TITLE
name_muni da Read_municipality de 1991

### ISSUE THREAD

**Issue by babisan08** [ipeaGIT/geobr#100]
O nome dos  municípios (code_muni) está todo em caixa alta, ou seja, está fora do padrão do pacote na função read_municipality do ano de 1991.

**Comment by rafapereirabr** [comment]
Ok, a correção precisa ser feita no prep. [Aqui tem algumas soluções para esse tipo de problema](https://stackoverflow.com/questions/11672050/how-to-convert-not-camel-case-to-camelcase-in-r).

**Comment by rafapereirabr** [comment]
Oi @babisan08 , conseguiu fazer a correcao do prep para fecharmos esse issue?

**Comment by babisan08** [comment]
Sim @rafapereirabr . Pode fechar.
