### ISSUE TITLE
translate read_biomes.R to Python python dev

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#108]
For this translation, use the following scripts as a reference:

- R function [read_biomes.R](https://github.com/ipeaGIT/geobr/blob/master/r-package/R/read_biomes.R)
- R test [test-read_biomes.R](https://github.com/ipeaGIT/geobr/blob/master/r-package/tests/testthat/test-read_biomes.R)

a python script: 

- [read_state.py](https://github.com/ipeaGIT/geobr/blob/master/python-package/geobr/read_state.py)

**Comment by JoaoCarabetta** [comment]
Translated in #112

**Comment by rafapereirabr** [comment]
@CaioNG , could you please check if the function is working as expected, please?

**Comment by rafapereirabr** [comment]
Function has been translated. Closing this for now. We will run some tests with users in a next step
