### ISSUE TITLE
Include 2010 data in `./data`

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#12]
Include table with metadata of all geometries `./data`. Something like:

|municipality_name|municipality_code|state_name|state_code|region_name|state_initials|region_code|geom|
|-----|-----|-----|-----|-----|-----|-----|-----|
|...|...|...|...|...|...|...|...|

* Na coluna `geom` informar dados referentes aos municipios

**Comment by CaioNG** [comment]
salvei em rds e txt, ficou um pouco grande.

**Comment by rafapereirabr** [comment]
Ok. Colocar la o arquivo na pasta `./data` do pacote e eu dou uma olhada.

abs!

Rafa

**Comment by rafapereirabr** [comment]
Otimo. Fiz uma nova versão usando a tabela de documentação do Censo 2010. Agora o arquivo tem mais colunas e mesmo assim mais compacto. Agora só falta conseguir fazer upload. rsrsrs
