### ISSUE TITLE
exporting shapefiles

### ISSUE THREAD

**Issue by gabrieltirintan** [ipeaGIT/geobr#125]
Hello, good afternoon.

I'm trying to export the shapefiles that i download by geobr and then read then in QGIS. I just can't save this shp in a right way, they always come wrong.
What's the best way to do that?

Thanks for atention!!

**Comment by rafapereirabr** [comment]
Hi Gabriel. Could you share the code you’re using ?

**Comment by gabrieltirintan** [comment]
Hi Rafael, like this?
I only download the shp but i don't let the fails in the script. Cause of it it's very short...
__________________________________ 

## Get IBGE data 

####################################################

## sidra = Sistema IBGE de recuperação automática
## API's = http://api.sidra.ibge.gov.br/
## somente os dados disponíveis em: https://sidra.ibge.gov.br/home/cnt/nordeste
#install version available on cran
install.packages("sidrar")
library(sidrar)

#To install the development version hosted on Github:
library(devtools)
install_github("rpradosiqueira/sidrar")

########################
## Pesquisa Nacional por Amostra de Domicílios Contínua - PNAD Contínua
install.packages("PNADcIBGE")
library(PNADcIBGE)

########################
## geobr -> munipal shapefiles and geografical information
install.packages("geobr")
library(geobr)

#####################################################

#using geobr package
#download brazil's city list until 2010 -> 5573 citys
municipal_seat<-read_municipal_seat(year = "2010")
length(municipal_seat)
is(municipal_seat)
municipios_brasil<-data.frame(municipal_seat)
write.table(municipios_brasil, file = "municípios_brasil")

# download brazilian conservation units data and shape
conservation_units<-read_conservation_units(201909, tp = "original")

# read_country -> download a shapefile of Brazil as a sf object
# data until 2018
brasil<-read_country(year = "2018", tp = "original")

# read_municipality -> download brazilian city's shapefile as sf object
municípios<-read_municipality(code_muni = "all", year = NULL, tp = "simplified")

# read_urban_area -> download brazilian urban areas as sf onject
áreas_urbanas<-read_urban_area(year = 2015, tp = "simplified")

**Comment by rafapereirabr** [comment]
Gabriel, qual linha de codigo voce usou para salvar o shapefile? Essa aqui eh a maneira correta.
```
library(geobr)
library(sf)

# download geobr data
muni <- read_municipality()

# save shpa file
st_write(muni, "muni.shp") # salvar shapefile
st_write(muni, "muni.gpkg")  # salvar geopackage (recomendado)
```

**Comment by gabrieltirintan** [comment]
Eu tinha tentado usar write.table e write.csv para depois criar os shapes no QGIS, mas não deu certo. 
Muito obrigado Rafael!!

**Comment by rafapereirabr** [comment]
@gabrieltirintan , o geobr trabalha com objeto espacial no `R` de clase `sf data.frame`.  Esse arquivo não tem como ser salvo com um `.csv`.  Voce precisa usar a função `sf::st_write`.  Estou fechando esse issue
