### ISSUE TITLE
multipla contagem de estados em 1991

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#128]
A base de estados de 1991 tem o mesmo problema de multipla contagem de unidades espaciais semelhante ao issue #89

**Comment by rafapereirabr** [comment]
Caio, consegiu avançar com esse issue?

**Comment by CaioNG** [comment]
termino hoje.

**Comment by rafapereirabr** [comment]
valeu! terminado. A base continua com 29 observacoes por conta de `Litígio PI/CE` e `Distrito estadual de Fernando de Noronha (PE)`
