### ISSUE TITLE
upcoming sf will break geobr on CRAN

### ISSUE THREAD

**Issue by edzer** [ipeaGIT/geobr#129]
See https://win-builder.r-project.org/incoming_pretest/sf_0.9-0_20200319_213604/reverseDependencies/summary.txt

and https://www.r-spatial.org/r/2020/03/17/wkt.html

If you test for `crs[[2]]` you no longer get the proj4string, but the wkt representation of a CRS. this breaks your package test(s).

**Comment by rafapereirabr** [comment]
Thank you for the heads up, @edzer !
