### ISSUE TITLE
Error when cloning git repo in Windows

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/geobr#137]
Hi!
I'm having the following issue when I try to clone the repo on my Windows machine. I get this error message at the end of the cloning message:

```
error: invalid path 'python-package/examples/2. What is the furthest place from a health facility?.ipynb'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

According to [this source](https://brendanforster.com/notes/fixing-invalid-git-paths-on-windows/) I suspect that the question mark on the file path is causing this issue, and removing it should be enough.

**Comment by JoaoCarabetta** [comment]
Try it now

**Comment by kauebraga** [comment]
Works fine now, thanks!
