### ISSUE TITLE
Include python to Travis

### ISSUE THREAD

**Issue by JoaoCarabetta** [ipeaGIT/geobr#138]
At some point, we should integrate Travis to the python branch. Every time a PR is submitted it fails and it is quite confusing and definitely not helpful.

**Comment by rafapereirabr** [comment]
Ideally, we should have a separate Travis for the Python and R directories. Is that possible?

**Comment by JoaoCarabetta** [comment]
I updated the `.travis.yaml` file to support python and R testing. I am still testing it given that the R build takes some time to finish.

**Comment by JoaoCarabetta** [comment]
@rafapereirabr the python build seems fine, but I am getting an error in the R build. It seems it cannot find the `devtools` in that R version. I just copied the instructions that you already had...

Can you take a look?
https://travis-ci.org/github/ipeaGIT/geobr/jobs/673529808

**Comment by rafapereirabr** [comment]
I believe this was caused by a typo. The devtoolss package name was written as 'devtool' in the `.travis.yaml file ` . I have fixed this so it should work now.... fingers crossed

**Comment by JoaoCarabetta** [comment]
It is passing 👍
