### ISSUE TITLE
Disregard 'Jupyter Notebook' code on github stats

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#139]
@JoaoCarabetta , the github code bar says our repo is comprised of:
- 87.9% Jupyter Notebook  
- 10.3% R 
- 1.8% Python 

Can we disregard `Jupyter Notebook` code for this count and keep it only with R and Python? Perhaps @kauebraga already knows how to do this.

**Comment by JoaoCarabetta** [comment]
I saw that as well. It is very odd because there are only 2 jupyter notebooks.

I will take a look into it

**Comment by JoaoCarabetta** [comment]
Solved!

I added a file called `.gitattributes` that takes care of that

**Comment by rafapereirabr** [comment]
thanks
