### ISSUE TITLE
Incluir dados e função de áreas de risco

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#14]
Oi Guilherme, use aqueles shape files de áreas de risco do IBGE que usamos no outro trabalho do ODS. Ok? abs

**Comment by guiducar** [comment]
Oi Rafael. Desculpe a demora. Não entendi o que é para fazer, é pra inserir o "indicador_11_5_1" do ODS no shape file da área de risco por código da UF?

**Comment by rafapereirabr** [comment]
Oi Giulherme. É só para inserir o shape file do IBGE com as áreas de risco
