### ISSUE TITLE
Criar função para gerar/atualizar tabela de metadados

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#15]
Criar função que varre todos arquivos na pasta `./geobr/data` e atualiza tabela com metadados do pacote. Exemplo abaixo de tabela de metadados

|geo|year|code|download_path|
|-----|-----|-----|-----|
|municipio| 2001|33 | http://www.ipea.gov.br/geobr/municipio/2001/33MU.rds |
|micro_regiao| 2016|17 | http://www.ipea.gov.br/geobr/micro_regiao/2016/17MI.rds|
|...| ...|... | ...|

**Comment by Pauloaraujoo** [comment]
indice <- data.frame(matrix(ncol = 4, nrow = 0))
colnames(indice) <- c("geo","year","code","download_path")

geo=list.files("//storage3/geobr/data")
for (a in geo) {
    ano=list.files(paste("//storage3/geobr/data",a,sep="/"))
  for (b in ano) {
    estado=list.files(paste("//storage3/geobr/data",a,b,sep="/"))
  for (c in estado) {
    indice[nrow(indice) + 1,] = list(a,b,substr(c, 1, 2),paste("http://www.ipea.gov.br/geobr",a,b,c,sep="/")) 
  }
 }
}

#para salvar             
#write.csv2(indice,"//storage3/geobr/indice.csv")

**Comment by Pauloaraujoo** [comment]
#corrigindo programação

indice <- data.frame(matrix(ncol = 4, nrow = 0))
colnames(indice) <- c("geo","year","code","download_path")

geo=list.files("//storage3/geobr/data")
for (a in geo) {
  ano=list.files(paste("//storage3/geobr/data",a,sep="/"))
  for (b in ano) {
    estado=list.files(paste("//storage3/geobr/data",a,b,sep="/"))
    for (c in estado) {
      indice[nrow(indice) + 1,] = list(a,b,substr(c, 1, 2),paste("http://www.ipea.gov.br/geobr/data",a,b,c,sep="/"))
    }
  }
}

#para salvar
#write.csv2(indice,"//storage3/geobr/indice.csv")
