### ISSUE TITLE
Export census tracts to shapefile error

### ISSUE THREAD

**Issue by epkresch** [ipeaGIT/geobr#151]
I came across the following error when trying to export a census tract data-set to a shapefile. I was able to easily export other datasets - such as state and municipalities - but received a GDAL error when trying to export the census tracts.

Here is the output of my code. I first grabbed the municipalities of Rio and it exported perfectly. When I grabbed the census tracts for Manaus in 2000, I received the error:

<img width="1260" alt="Screen Shot 2020-05-02 at 9 59 50 AM" src="https://user-images.githubusercontent.com/27973401/80986107-19115f80-8dfe-11ea-9dcb-95f9e1088f5f.png">

**Comment by rafapereirabr** [comment]
Hi Evan. This is a similar problem reported on issue #135. We will address this in our database. In the meantime, you can use a simple fix using `st_cast{sf}`:
```
cntr <- sf::st_cast(cntr, "MULTIPOLYGON")

sf::st_write(cntr , 'cntr .shp')
```

**Comment by rafapereirabr** [comment]
Hi @epkresch . I've used sf::st_cast(cntr, "MULTIPOLYGON") to fix the 2010 census tract data set of Manaus. Could you please check if this solved the problem you were facing?

**Comment by epkresch** [comment]
Yes, that worked!! Thanks so much for the solution.

**Comment by rafapereirabr** [comment]
Thank you @epkresch !
