### ISSUE TITLE
'geo' object not found

### ISSUE THREAD

**Issue by RikFerreira** [ipeaGIT/geobr#153]
Hello, does anyone reported the following error after updating to R 4.0.0:

`Error in eval(e, x, parent.frame()) : 'geo' object not found`

This error shows up after any `read_` call.

Package version: 1.3

R version:
```
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          4                           
minor          0.0                         
year           2020                        
month          04                          
day            24                          
svn rev        78286                       
language       R                           
version.string R version 4.0.0 (2020-04-24)
nickname       Arbor Day
```

**Comment by rafapereirabr** [comment]
Hi @RikFerreira . Our server has been unstable since yesterday. We are working to fix this asap. I'll keep you posted here

**Comment by rafapereirabr** [comment]
Hi all. Our server is back online. Please try using the package again and let us know if it's working on your end.

**Comment by RikFerreira** [comment]
Up and running. Thanks for the attention.
