### ISSUE TITLE
New micro-regiao data for 2019

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#157]
- [x] micro-regiao

**Comment by rafapereirabr** [comment]
Oi Barbara, conseguiu avançar com isso aqui?

**Comment by rafapereirabr** [comment]
Oi Barbara, conseguiu avançar com isso aqui?

**Comment by babisan08** [comment]
Sim. Está pronto. Já coloquei no repositório.

**Comment by rafapereirabr** [comment]
@CaioNG . Voce pode incluir a base na pasta da rede?

- rodar o prep
- salvar arquivo na pasta
- atualizar arquivo de metadata

**Comment by CaioNG** [comment]
resolvido

**Comment by rafapereirabr** [comment]
Valeu.
