### ISSUE TITLE
New unidades da federacao data for 2019

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#159]
- [x] unidades da federacao

**Comment by rafapereirabr** [comment]
Pedro, a atualizacao do prep ficou pronta?

**Comment by PedroJorge7** [comment]
Sim. Tanto o prep como o read. Rodei os scripts utilizando a nova função e deu tudo certo :)

**Comment by rafapereirabr** [comment]
Opa. Só reabrindo aqui porque ainda nao atualizamos a base para os usarios. Mas ja ja resolvo isso

**Comment by rafapereirabr** [comment]
@CaioNG . Voce pode incluir a base na pasta da rede?

- rodar o prep
- salvar arquivo na pasta
- atualizar arquivo de metadata

**Comment by CaioNG** [comment]
Resolvido mas de maneira descontente. devido aos problemas de encoding para corrigir os nomes não pude paralelizar, tive de fazer um "for".

**Comment by rafapereirabr** [comment]
valeu
