### ISSUE TITLE
Incluir scripts usados para tratamento dos dados brutos

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#16]
Passar para pasta `./geobr/prep_data` os scripts em R que foram usados para tratamento dos dados brutos. Isso serve para fins de documentação

**Comment by rafapereirabr** [comment]
Ja incluidos scripts para as seguintes funções/dados:

- `read_country`
- `read_state`
- `read_meso_region`
- `read_micro_region`
- `read_municipality`
- `read_statistical_grid`

Falta incluir ou corridir para as seguintes:

- `read_weighting_area`
- `read_census_tract`

**Comment by Pauloaraujoo** [comment]
`read_weighting_area `incluído.

**Comment by rafapereirabr** [comment]
> `read_weighting_area `incluído.

Maravilha!

**Comment by rafapereirabr** [comment]
Todos arquivos `prep_` incluidos. Soh falta atualizar o arquivo de metadados para incluir dados de setores censitarios.
