### ISSUE TITLE
error reading from connection (temporary, or related to new data?) 

### ISSUE THREAD

**Issue by schmert** [ipeaGIT/geobr#161]
**This may be just a temporary problem at the IBGE end, but...**

> library(geobr) 

> BR = read_country() 
Error in readRDS(path) : error reading from connection 

> BR = read_country(year=2010) 
Error in readRDS(path) : error reading from connection 

> BR = read_country(year=2019) 
Error in readRDS(path) : error reading from connection 

> read_municipality(code_muni = 'RJ') 
Error in readRDS(path) : error reading from connection

**Comment by rafapereirabr** [comment]
Hi Carl. I think updating geobr to the latest version will solve the problem, but please let me know if the problem persists. 

Rafa

Rafael H.M. Pereira

**Comment by schmert** [comment]
No, that wasn't the problem.  Everything works fine 12 hours later without any update.  So it likely was a temporary connectivity problem (?), unrelated to the new data (?).

**Comment by rafapereirabr** [comment]
It was probably a temporary connectivity problem. Our serves have been unstable over the past few days but I hope this is all solved now. I'll close this issue for now but please to not hesitate to get in touch if you have the same problem again.
