### ISSUE TITLE
Possible problem in 1991 data

### ISSUE THREAD

**Issue by lucascr91** [ipeaGIT/geobr#163]
Hi, I type

`mun_91=read_municipality(code_muni=35,year=1991)`

And get the whole database instead of just the Sao Paulo municipalities. This command works for 2018, though. Any guess on what is going on here?

**Comment by rafapereirabr** [comment]
Hi Lucas. Thanks for the feedback.

From the year 2000 onward, municipality data sets are stored separately by state. Before the 2000s, there is a single file for each year covering all municipalities. This is due to how IBGE organizes the original data and we ended up incorporating that in how we organize our files.

In any case, we should include a `subset()` operation inside the function so that it returns exactly what the user requests. This is a minor bug that has been in our radar. We hope we can address it for the next version of `geobr`.

**Comment by rafapereirabr** [comment]
Hi @PedroJorge7 , any progress with this issue?

**Comment by PedroJorge7** [comment]
Hi @rafapereirabr. This issue has already been corrected and in the next update of geobr it will be ok. But we still need to fix other problems, like including the code_state and name_state columns. I believe that in the coming days this will also be resolved :)

**Comment by JoaoCarabetta** [comment]
I'll be working in this feature to the new Python version. It hope to update it soon.

**Comment by rafapereirabr** [comment]
I've updated the `read_municipality.R`  so this issue should be fixed in `R`. @CaioNG and @PedroJorge7 are also working to add more columns to the data sets before 1992, including `code_state`, `name_state`, etc. This will soon make this function much more versatile and complete for users

**Comment by theiostream** [comment]
I'm still facing this problem with the 1991 data:

```
> read_municipality(code_muni = 'all', year = 1991) %>% st_drop_geometry() %>% count(code_muni) %>% arrange(desc(n)) %>% tibble()
Using year 1991
Loading data for the whole country

# A tibble: 4,493 x 2
   code_muni     n
       <dbl> <int>
 1        NA    31
 2   2103703    18
 3   2101301    16
 4   2102606     9
 5         0     6
 6   1508308     5
 7   1500909     4
 8   3300100     4
 9   2100204     3
10   2103109     3
# … with 4,483 more rows
```

**Comment by rafapereirabr** [comment]
Hi @theiostream . According to IBGE original data, disputed territories have a `code_muni` equals to `0`.

```R
library(geobr)
library(magrittr)
library(dplyr)
library(sf)
library(mapview)

all <- read_municipality(code_muni = 'all', year = 1991)

b <- subset(all, code_muni==0)
b

> Simple feature collection with 6 features and 4 fields
> geometry type:  MULTIPOLYGON
> dimension:      XY
> bbox:           xmin: -41.436 ymin: -5.419055 xmax: -40.91003 ymax: -3.305793
> geographic CRS: SIRGAS 2000
>      code_muni     name_muni code_state abbrev_state                           geom
> 271          0         Pi/Ce          0         <NA> MULTIPOLYGON (((-41.42387 -...
> 308          0         Pi/Ce          0         <NA> MULTIPOLYGON (((-41.38328 -...
> 398          0         Pi/Ce          0         <NA> MULTIPOLYGON (((-41.06881 -...
> 4602         0 Litígio PI/CE          0         <NA> MULTIPOLYGON (((-41.18117 -...
> 4603         0 Litígio PI/CE          0         <NA> MULTIPOLYGON (((-41.42387 -...
> 4604         0 Litígio PI/CE          0         <NA> MULTIPOLYGON (((-41.2132 -3...

```

**Comment by theiostream** [comment]
@rafapereirabr Good to know! The other issue, however, is with there being multiple entries of the same `code_muni` in the dataset.

**Comment by rafapereirabr** [comment]
> @rafapereirabr Good to know! The other issue, however, is with there being multiple entries of the same `code_muni` in the dataset — something that doesn't happen for other years.

Hi @theiostream , I've fixed this problem of duplicated municipalities in the data set. Please let us know if there is any remaining issue of whether we can close this one

**Comment by theiostream** [comment]
All seems well for me!

**Comment by rafapereirabr** [comment]
Thanks. closing this issue for now.
