### ISSUE TITLE
Filtrar Municípios 

### ISSUE THREAD

**Issue by PauloSantana2019** [ipeaGIT/geobr#164]
Considerando o tamanho dos arquivos seria interessante a possibilidade de filtrar os dados antes de serem carregados
Ex Dados de Municípios carregados apenas para alguns estados 

Atualmente temos que carregar todo o Brasil e depois filtrar. 

No R a possiblidade de especificar um vetor com os estados possibilitaria maior flexibilidade e padronização (declaração de variável para o conjunto de estados objeto de estudo)

**Comment by rafapereirabr** [comment]
Oi Paulo. Obrigado pelo feedback. Ha um tempo estamos pensando em incluir essa opção de passar como input um vetor de estados ou municipios. Vamos avaliar como podemos implementar isso para proxima versao. Caso voce queira implementar isso, fique a vontade para fazer um pull request.

**Comment by rafapereirabr** [comment]
> Considerando o tamanho dos arquivos seria interessante a possibilidade de filtrar os dados antes de serem carregados
> Ex Dados de Municípios carregados apenas para alguns estados
> 
> Atualmente temos que carregar todo o Brasil e depois filtrar.
> 
> No R a possiblidade de especificar um vetor com os estados possibilitaria maior flexibilidade e padronização (declaração de variável para o conjunto de estados objeto de estudo)

Paulo, na versão atual do `geobr` já é possivel ler os dados apenas dos municipios de um determinado estado. Por exemplo, essa linha aqui carrega apenas os municipios de Santa Catarina. Isso resolve o issue pra voce?

` muni <- geobr::read_municipality(code_muni = 'SC')`

**Comment by rafapereirabr** [comment]
O geobr permite fazer a leitura direta de estados especificos.


```
library(geobr)

# read data of municipalities in a state
   ex1 <- geobr::read_municipality(code_muni = 'RJ')
   ex2 <- geobr::read_municipality(code_muni = 33)

# keep selected municipalities
   selected <- subset(ex1, code_muni %in% c(3300100, 3300258) )
   selected <- subset(ex1, code_muni %in% c('Angra Dos Reis', 'Arraial Do Cabo') )
```

**Comment by PauloSantana2019** [comment]
Esta atualização resolve o issue. 
Muito obrigado !


Em sábado, fevereiro 13, 2021, 12:43 PM, Rafael H M Pereira <notifications@github.com> escreveu:




O geobr permite fazer a leitura direta de estados especificos.
library(geobr)

# read data of municipalities in a state
   ex1 <- geobr::read_municipality(code_muni = 'RJ')
   ex2 <- geobr::read_municipality(code_muni = 33)

# keep selected municipalities
   selected <- subset(ex1, code_muni %in% c(3300100, 3300258) )
   selected <- subset(ex1, code_muni %in% c('Angra Dos Reis', 'Arraial Do Cabo') )
