### ISSUE TITLE
error with all read_ functions

### ISSUE THREAD

**Issue by gabrielmariante** [ipeaGIT/geobr#166]
Hello, 

All reading functions result in the same error, as if something is missing with the input files. Below, the simplest example when reading all the states. The same happens if I add arguments, and if I try using other read functions (like read_municipality).

```

> all_states = read_state()

Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
```

Any ideas on what I might be missing?
Thanks!

**Comment by gabrielmariante** [comment]
Update: it seems like the first time running any read_function, the error is as follows:

```

> mun <- read_municipality(code_muni=1200179, year=2017)

Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  SSL certificate problem: certificate has expired
```

And after that, trying to run again results in the error in the first post

**Comment by gmendesb** [comment]
Same here

**Comment by rafapereirabr** [comment]
I just ran a few functions and they  worked fine. The server where we host the data at Ipea might have been for a couple hours. This should be a rare event. Please try again and let me know if the problem persists.

**Comment by gabrielmariante** [comment]
Hi, thanks for getting back! The error still persists with me.
Should I be aware of any R-version issues or packages that need to be loaded other than "geobr" itself? 
I'm having this problem on Mac OS, and it's a new computer with the latest version from R installed. I actually ran a similar code on an older Windows PC, and did not have that error.
Thanks again

**Comment by JoaoCarabetta** [comment]
I just got the same error using the R version on Mac OS, but not the Python version.

It seems to be that Mac OS + R 4.0.0 causes that error.

**Comment by gmendesb** [comment]
I just re-installed the packages httr and sf and that works now.

**Comment by JoaoCarabetta** [comment]
It works here as well, maybe we should force the version of sf and httr packages

```
sf_0.9-3
httr_1.4.1
```

**Comment by JoaoCarabetta** [comment]
I opened an PR wih

**Comment by rafapereirabr** [comment]
Thanks for your help @JoaoCarabetta ! Closing the issue now.

**Comment by gabrielmariante** [comment]
Worked for me as well, thanks for the help!
