### ISSUE TITLE
What is the CRS of 'read_census_tract' data?

### ISSUE THREAD

**Issue by JoaoCarabetta** [ipeaGIT/geobr#167]
Question received by email. @rafapereirabr do you know?
```
Boa tarde, João, tudo bem?

Sou o Flávio, estava utilizando a biblioteca em python geobr
disponível no github; aliás, obrigado por essa disponibilização; e me
surgiu uma dúvida, se puder me ajudar serei grato. O método
geobr.read_municipality() em suas informações destaca que o CRS é o
4674; já em geobr.read_census_tract() o CRS não é explicito. Saberia
me informar se as geometrias seguem o mesmo CRS 4674?

Abraços
```

**Comment by rafapereirabr** [comment]
Hi Joao. All data sets in `geobr` use the same Geodetic reference system "SIRGAS2000" and CRS(4674), which is the official projection used by IBGE. Perhaps we can add this information to the package description, instead of mentioning this in each function of the documentation.

**Comment by JoaoCarabetta** [comment]
It is in the README already.

**Comment by rafapereirabr** [comment]
Hi Joao. This modification to the `README.md` has broken the `list_geobr` function in R. I have fixed it already but could you please check if the python version is working correctly ?
