### ISSUE TITLE
new data set: isolated rural communities

### ISSUE THREAD

**Issue by theiostream** [ipeaGIT/geobr#168]
As part of the BC250, IBGE releases geographic data about isolated rural communities. For 2017, they are available in ftp://geoftp.ibge.gov.br/cartas_e_mapas/bases_cartograficas_continuas/bc250/versao2017/shapefile/Localidades_v2017.zip.

The data are simple – it's just points.

It'd be great to see this in `geobr`.

**Comment by rafapereirabr** [comment]
Hi Daniel. thanks for the suggestion. I had looked at these data some time ago and I remember the quality of the data was a bit problematic, with many rural communities located in urban areas. So I don't think we will be including this data set in `geobr`. However, I believe the best alternative here would be to include in `geobr` the census tracts of the Census of Agriculture (Censo Agropecuário) conducted by IBGE.
This data set is available on this [link](ftp://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_de_setores_censitarios__divisoes_intramunicipais/censo_agro_2017/)

**Comment by theiostream** [comment]
Thanks for the response. I'm trying to use this dataset as a last resource to locate polling stations (seções eleitorais) that are basically impossible to geocode – and the name of the isolated rural community is important to that end. I checked the Censo Agropecuário shapefiles and, at a first glance, they don't seem to have that information :(.

This is likely beyond the scope of this issue, but if you're able to do so, I'd appreciate suggestions on more reliable databases I might be able to use with similar information. (Also – when you say that the rural communities are inside urban areas, how exactly are you determining urban areas?)

**Comment by rafapereirabr** [comment]
Adding electoral districts data to `geobr` has been in our plans for a long time (see issue #3 ), but this is tricky and it's not in our top priorities at the moment. We would be glad to receive a contribution on this front. I suggest you have a look at the work of @RodrigoMenegat in this repository [here](https://github.com/estadao/como-votou-sua-vizinhanca/blob/master/code/voronois-2018.ipynb).

In the meantime, I will close this issue and open a new one to include the Censo Agropecuário shapefiles in `geobr`.

ps. I plotted the 'isolated rural areas' on the map and I could see some of them located neighborhoods I know. You can download Brazilian urban areas in with `geobr::read_urban_area()`.

**Comment by theiostream** [comment]
Just for future reference: I just realized the Censo Agropecuário has updated the CNEFE address base for rural areas; which likely fulfills the requirements I listed above. Let's see how that works out.

**Comment by andresfchamorro** [comment]
@theiostream @rafapereirabr any idea if there is a shapefile of populated settlements? I looked at the census tract files but the majority don't have any names beyond district. looking for some of the communities located with black dots in this map for example: https://www.ipece.ce.gov.br/wp-content/uploads/sites/45/2021/12/mapas_municipais_Amontada_2021.pdf Any help is appreciated!

**Comment by rafapereirabr** [comment]
The best official data source in this case would be the statistical grid, created by IBGE. This data set can be downloaded using the [`read_statistical_grid()` function](https://ipeagit.github.io/geobr/reference/read_statistical_grid.html).

If you want to download these data for a particular city or state, I'd recommend having a look at the [`grid_state_correspondence_table()`](https://ipeagit.github.io/geobr/reference/grid_state_correspondence_table.html) function as well.
