### ISSUE TITLE
Create function of AMC for municipalities

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#17]
Avaliar se é possível aproveitar o código em Stata do  Philipp Ehrl (professor da Univ. Catolica de Brasilia e bolsista na DIRUR). Ele publicou uma [nota na Estudos Economicos sobre o código](http://www.revistas.usp.br/ee/article/view/106909) e o código está disponível [aqui](https://sites.google.com/site/philippehrl/Ehrl_AMCgeneration_EE.zip?attredirects=0).

**Comment by igorfnasc** [comment]
@rafapereirabr , o link com a nota não está funcionando. Estou indo apenas pelo código.

**Comment by rafapereirabr** [comment]
Ok. Esse link aqui deve funcionar http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0101-41612017000100215

**Comment by rafapereirabr** [comment]
Oi Igor, voce pode passar o desenvolvimento das AMCs para outro branch to pacote? Dai depois que estiver funcionando a gente faz um merge. É que agora nessa fase de desenevolvimento sempre ficam um 'fios soltos' e que atrapalham os testes de outras mudanças no pacote. 

quando fui fazer um teste hoje, por exemplo, deu essa mensagem aqui de erro:

```
devtools::load_all('R:/Dropbox/git_projects/geobr')

>Loading geobr
>Error in FUN(X[[i]], ...) : 
>  bad restore file magic number (file may be corrupted) -- no data loaded
>In addition: Warning message:
>file ‘_Crosswalk_pre.rda’ has magic number 'X'
>  Use of save versions prior to 2 is deprecated 
```

**Comment by igorfnasc** [comment]
Sem problemas!

**Comment by igorfnasc** [comment]
@rafapereirabr ,

aparentemente é um problema geral. Deletei esse arquivo, tentei rodar a documentação e acabei encontrando o mesmo erro. 
file ‘brazil_2010.RData’ has magic number 'RDX3'

**Comment by rafapereirabr** [comment]
Oi Igor. Avançou na construção das AMCs ?

**Comment by igorfnasc** [comment]
Pouco avanço. Nos próximos dias registro o que foi avançado.

**Comment by rafapereirabr** [comment]
@PedroJorge7 , could please share here the ftp link to download IBGE's excel spreadsheet with the history of municipality emancipations ?

**Comment by PedroJorge7** [comment]
Hi @rafapereirabr. I think that Phillip use this excel file (ftp://geoftp.ibge.gov.br/organizacao_do_territorio/estrutura_territorial/evolucao_da_divisao_territorial_do_brasil/evolucao_da_divisao_territorial_do_brasil_1872_2010/municipios_1872_1991/Documentacao/pop_mun_TUR_1872_a_2010.xls)

**Comment by rafapereirabr** [comment]
@CaioNG , Voce pode retormar isso aqui ?

**Comment by CaioNG** [comment]
Eu estou reorganizando a programação da função, estou tbm fazendo um exemplo reproduzível no stackoverflow para o problema de ordem da base. Porem como pela logica da função a ordem não deveria importar tanto acredito que a um outro erro que ainda não achei no meio da função. Por isso estou seguindo com uma visão bem detalhada.

**Comment by rafapereirabr** [comment]
@CaioNG  e @PedroJorge7 . Como está o avanço desse issue? O que está faltando? Podemos ter uma solução até o final desse mês?

**Comment by CaioNG** [comment]
Oi @rafapereirabr , progredimos pouco. Entender o que esta acontecendo diferente do stata para o R tem sido uma grande dificuldade. Acredito sim que podemos ter uma resolução até o final do mês se começarmos a trabalhar mais em paralelo ao invés de juntos como estamos fazendo eu e @PedroJorge7. já falei com Pedro e dividimos as tarefas.

**Comment by rafapereirabr** [comment]
Como vocês dividiram as tarefas? Conseguiram avançar em quais?

**Comment by CaioNG** [comment]
Sim conseguimos avançar, o @PedroJorge7 consegui-o identificar a diferença em organização dos municípios e eu consegui identificar erros de aplicação dentro do algoritmo. No momento estou bolando uma solução para corrigir esses erros. Assim que eu tiver uma solução fechada pretendo me reunir com Pedro para testarmos o algoritmo e se for necessário planejar passos futuros. 

Respondendo mais claramente a sua primeira pergunta, pedi para @PedroJorge7 tentar solucionar a questão da diferença entre ordem dos municípios entre o algoritmo do stata e o R, isso é necessário porque sem termos uma comparação clara entre o os dois procedimentos fica muito difícil de comparar. Enquanto isso eu fique verificando o código diretamente para achar possíveis erros de aplicação e tradução dos comandos, o que já era esperado ter mas era difícil de identificar.
