### ISSUE TITLE
data request: census tracts of the Census of Agriculture

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#171]
This data set is available on this link ftp://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_de_setores_censitarios__divisoes_intramunicipais/censo_agro_2017/

**Comment by rafapereirabr** [comment]
@Alandasilva , could you please create the `prep_ ` file for this data base?

**Comment by Alandasilva** [comment]
Ok @rafapereirabr , i'll start working on it.

**Comment by Alandasilva** [comment]
`prep_ `  file finished.

**Comment by rafapereirabr** [comment]
Thanks @Alandasilva . I've made some small edits to the file to simplify the code. The data is now available on `geobr` and it can be accessed with:

`agro <- read_census_tract(code_tract = 'ac', year=2017)`
