### ISSUE TITLE
geobr files cannot be used by plotly package to make interactive plots

### ISSUE THREAD

**Issue by fmgithub2017** [ipeaGIT/geobr#172]
I want to create interactive plots using the data retrieved from `geobr ` but it generates an error.

Related reported issues:
[Creating a interactive map on R using plotly](https://stackoverflow.com/questions/60684049/creating-a-interactive-map-on-r-using-plotly)
[In R, using geom_sf + frame and passing it to plotly::ggplotly gives me transitions error, what did I miss?](https://stackoverflow.com/questions/58003600/in-r-using-geom-sf-frame-and-passing-it-to-plotlyggplotly-gives-me-transiti)

Minimum example that works (using mapview package data):
```
library(plotly)
library(mapview)
data(franconia, package = "mapview")
plotly::plot_ly(franconia, split=~NUTS_ID, color=~SHAPE_AREA, alpha=1,showlegend = FALSE)
```

Minimum example that does not work (using geobr data):
`plotly::plot_ly(geobr::read_state(year=2018))`

 or
```
library(ggplot2)
p <- ggplot()+geom_sf(data=geobr::read_state(year=2018))
plotly::ggplotly(p)
```
The error message:
```
st_coordinates.sfc(sf::st_geometry(model)) : 
  not implemented for objects of class sfc_GEOMETRY  
```
The reason seems to be that geobr uses a sf subclass "sfc_GEOMETRY" instead of "sfc_MULTIPOLYGON". 

Is it possible to get around this issue?  (Plotly interactive features are very important for my research)

Thank very much. Other than that, geobr is excellent.

**Comment by rafapereirabr** [comment]
The cause of this problem is related to the issue #135. We will address this in our database. In the meantime, I believe you can use a simple fix using st_cast{sf}. Let me know if this works for you.

`cntr <- sf::st_cast(cntr, "MULTIPOLYGON")`

**Comment by fmgithub2017** [comment]
@rafapereirabr  , thank you very much, it worked!

Here is a minimum working example:
```
library(plotly)
library(sf)
library(geobr)
mab_br_states = geobr::read_state(year=2018)
plotly::plot_ly(sf::st_cast(mab_br_states, "MULTIPOLYGON"))
```

**Comment by rafapereirabr** [comment]
Hi @fmgithub2017 . I've used `sf::st_cast(cntr, "MULTIPOLYGON")` to the `state` data sets of 2018. Could you please check if this solved the problem you were facing?

**Comment by fmgithub2017** [comment]
Hey @rafapereirabr , of course. And yes, this worked:
```
utils::remove.packages('geobr')
devtools::install_github("ipeaGIT/geobr", subdir = "r-package")
library(plotly)
library(sf)
library(geobr)
map_br_states = geobr::read_state(year=2018)
plotly::plot_ly(map_br_states)
```
Thank you

**Comment by rafapereirabr** [comment]
Thanks!
