### ISSUE TITLE
install_github: unexpected if

### ISSUE THREAD

**Issue by albersonmiranda** [ipeaGIT/geobr#173]
Na instalação da devel version, a função `read_state` está com a seguinte crítica:

```
.../geobr/R/read_state.R:62:5: 'if' inesperado
61:     
62:   } if
        ^
ERROR: unable to collate and parse R files for package 'geobr'
```

**Comment by rafapereirabr** [comment]
Thank you for the heads up. I just fixed this error and the dev version of the package should be working now.
