### ISSUE TITLE
read_weighting_area() has wrong codes

### ISSUE THREAD

**Issue by theiostream** [ipeaGIT/geobr#174]
Okay, this is a weird one.

If we run `read_weighting_area()` for Rio, here's what we get:

```
> read_weighting_area(code_weighting = 3304557, simplified = F)$code_weighting_area
[1] 3304557006076 3304557006077 3304557006078 3304557006079 3304557006072 3304557006073 3304557006074 3304557006075 3304557006070 3304557006200
 [11] 3304557006071 3304557006089 3304557006087 3304557006088 3304557006085 3304557006086 3304557006083 3304557006084 3304557006081 3304557006082
...
```

Note that all weighting area codes have **6** as their tenth digit.

Now, if you head to https://censo2010.ibge.gov.br/apps/areaponderacao/ and pick some random weighting areas in Rio, you'll see that all weighting area codes have **5** as their tenth digit.

If we look at the Ipanema weighted tract on the Census website, we have code `3304557005047`. But here's what happens if we try to run it on the `geobr` output:

```
> ap %>% filter(code_weighting_area == 3304557005047)
Simple feature collection with 0 features and 3 fields
bbox:           xmin: NA ymin: NA xmax: NA ymax: NA
CRS:            EPSG:31983
[1] code_weighting_area code_muni           code_state          geom               
<0 linhas> (ou row.names de comprimento 0)
```

And if we replace the **5** with a **6**:

```
Simple feature collection with 2 features and 3 fields
geometry type:  MULTIPOLYGON
dimension:      XY
bbox:           xmin: 677756.1 ymin: 7470634 xmax: 679839 ymax: 7472545
CRS:            EPSG:31983
  code_weighting_area code_muni code_state                           geom
1       3304557006047   3304557         33 MULTIPOLYGON (((677767.3 74...
2       3304557006047   3304557         33 MULTIPOLYGON (((677767.3 74...
```

I have no idea why the `geobr` output has this +1000 offset on the weighting area codes, but this hinders any attempt to cross this data with Census microdata output. I suppose it's worth looking into?

**Comment by rafapereirabr** [comment]
This is very strange. The original shape file downloaded from IBGE's website  has a `6` in the 10th digit. Have you checked the code of weighting areas in the census microdata ? Does it use `5` or `6`?

**Comment by theiostream** [comment]
The microdata I'm using is from the Centro de Estudos da Metrópole, which means it was preprocessed. But that does use a **5**.

**Comment by rafapereirabr** [comment]
I've downloaded  and processed the weighting areas data sets again. This has been fixed now. Thanks for the heads up !

**Comment by rafapereirabr** [comment]
Ok, I've found the source of the problem. After the first publication of the weighting areas data set, IBGE has redefined the shape of a few cities, Rio de Janeiro included. This is odd, but I believe the must have changed 10th digit to differentiate between the original and redefined data sets. I have now fixed this for the city of Rio. I haven't checked the other cities yet

**Comment by theiostream** [comment]
Just to clarify – are `geobr`'s weighting areas the new ones or the old ones?

**Comment by rafapereirabr** [comment]
> Just to clarify – are `geobr`'s weighting areas the new ones or the old ones?
> 
> Like, are we changing back to the old ones for microdata compatibility, or are the shapefiles we are using the old ones?

This is a dilemma now. So far, we have been sharing the redefined areas. This is not a problem in cities like Rio, where IBGE has simply redrawn the boundaries of a few weighting areas (the number of areas is the same in both versions of the data set). However, in cities like Natal, they have combined weighting areas so that the number of areas is the **different** in the different versions of the data set.

We need to look further into this to decide which version we should be making available. I'm glad to hear your inputs on this.

**Comment by theiostream** [comment]
I'd allow for both versions to be downloaded, I suppose. You could pass `year = 2010` if you want the ones that are compatible with the Census, and `year = 201x` for the new ones.

**Comment by theiostream** [comment]
But yeah, I guess it's important to find out what was behind this redefinition. Is the IBGE using the new weighting areas in other surveys? Or maybe they're using these new areas internally for Censo 2010 analysis and they just haven't updated the public microdata to reflect the changes...?

**Comment by rafapereirabr** [comment]
Ok, so this is the response I got from a good friend who works at IBGE. I will update the data sets today, making sure we share the first release of the 2010 weighting areas.

> "A versão redefinada respondeu a demandas específicas dos municípios. Alguns deles não haviam respondido ao IBGE em tempo de incorporar. Então, estas áreas redefinidas  incorporam algumas solicitações dos municípios. De fato, os microdados (inclusive BME) estão ajustados a primeira versão das áreas de ponderação. Se não houver nenhum problema para o estudo que você está fazendo, sugiro utilizar a primeira versão para todo mundo. Facilita muito a operacionalização do trabalho. Para a segundo versão acho que seria necessário pedir uma tabulação especial"

**Comment by rafapereirabr** [comment]
I've replaced the files in our server to make sure we are sharing the weighting areas that were published in the first release, which are compatible with census microdata
