### ISSUE TITLE
Base de municípios com mais municípios que o correto

### ISSUE THREAD

**Issue by ctrovao** [ipeaGIT/geobr#176]
Caros colegas, 

Estou usando a função read_municipality e para todos os anos posteriores a 2010 o número de municípios que consta são 5572. Porém, o número de municípios que o IBGE considera é de 5570. Percebi que os municípios adicionais são Lagoa Mirim (4300001) e Lagoa Dos Patos (4300002). Como esses municípios não aparecem em outras bases do IBGE e, por isso, não se pode atribuir valores para variáveis que se pretende usar (número de pessoas, por exemplo), o gráfico fica com duas manchas cinzas no RS.

Gostaria de saber se vocês já corrigiram esse problema ou se tem algo que se possa fazer para que o gráfico não fique com essas manchas!

Agradeço a atenção!

**Comment by rafapereirabr** [comment]
Oi @ctrovao , o dado original do  IBGE trem esses dois poligonos a mais. Outra pessoa tambem ja tinha reclamado desse detalhe, e de fato esses poligonos sao imcompativeis com o resto da base, entao nós vamos retirar isso do dados. Enquanto isso, voce pode adotar uma solução mais imediata e simplesmente fazer um `subset`
 `subset( muni, code_muni != 4300001 )`

**Comment by ctrovao** [comment]
Olá Rafael!
Muito obrigado pela rápida resposta!
Funcionou direitinho!
Att
Trovão
    Em segunda-feira, 29 de junho de 2020 08:16:55 BRT, Rafael H M Pereira <notifications@github.com> escreveu:  
 
 


Oi @ctrovao , o dado original do IBGE trem esses dois poligonos a mais. Outra pessoa tambem ja tinha reclamado desse detalhe, e de fato esses poligonos sao imcompativeis com o resto da base, entao nós vamos retirar isso do dados. Enquanto isso, voce pode adotar uma solução mais imediata e simplesmente fazer um subset
subset( muni, code_muni != 4300001 )

**Comment by jorge-santos** [comment]
Também detectei esse problema. São duas lagoas do RS e não dois municípios. Existe uma cidade Lagoa dos Patos, mas é em MG (cod_ibge 3137304). Já enviei uma mensagem ao IBGE, alertando para o caso da Lagoa dos Patos.

**Comment by rafapereirabr** [comment]
pois, esse erro persiste no dado oringial compartilhado pelo IBGE e preciso aplicar esse filtro para remover essas lagoas dos anos mais recentes. Vou reabrir esse issue para lembrar disso na proxima atualzacao

**Comment by OlivazShai** [comment]
Me deparei com essa mesma questão recentemente, acredito que não seja um erro na base de dados do IBGE. Pelo que pude descobrir, há algum dispositivo constitucional que determina a inclusão dessas duas lagoas na área territorial do RS. Por conta disso, IBGE tem incluído esses dois polígonos na malha municipal desde 2001/2002, sob a classificação de "Áreas Estaduais Operacionais", como vemos [na descrição da malha](https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais/15774-malhas.html?=&t=sobre).

Não consegui localizar o dispositivo constitucional que determina essa questão, mas essas informações que citei podem ser lidas em algum detalhe [na descrição do produto de áreas territoriais](https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/15761-areas-dos-municipios.html?lang=pt-BR&t=saiba-mais-edicao). Apartentemente as áreas dessas duas lagoas devem ser incluídas nas áreas do RS e do Brasil como um todo. Continuo não entendendo perfeitamente a questão, mas pelo menos a presença desses dados na malha municipal não foi um erro do IBGE.

**Comment by rafapereirabr** [comment]
Obrigado pelo esclarecimento @OlivazShai !

**Comment by rafapereirabr** [comment]
Segundo o [site do IBGE](https://www.ibge.gov.br/geociencias/organizacao-do-territorio/estrutura-territorial/15761-areas-dos-municipios.html?lang=pt-BR&t=saiba-mais-edicao) indicado pelo @OlivazShai:
- "No Rio Grande do Sul, as áreas referentes às Lagoas dos Patos e Mirim foram incorporadas à área do Estado segundo a Constituição Estadual de 1988;"

Em geral, as pessoas nao usam esses poligonos. Entao eu criei um novo parâmetro na função que por 'default' dropa as duas lagoas `keep_areas_operacionais = FALSE`. Se o usuario quiser mantes esses dois poligonos, ele pode passar `keep_areas_operacionais = TRUE`.

```
#' @param keep_areas_operacionais Logic. Whether the function should keep the
#'        polygons of Lagoas dos Patos and Lagoa Mirim in the State of Rio Grande
#'        do Sul (considered as areas estaduais operacionais). Defaults to `FALSE`.
```
