### ISSUE TITLE
missing data from read_weighting_area 2010

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#179]
The original data set on weighting areas shared by IBGE in their ftp, the one we have been using so far, is incomplete. Currently, `geobr::read_weighting_area(year=2010)` only returns 2,838 observations. The full data set contains 11,016 observations with 10,185 unique weighting areas.

We need the adjust and run the `prep_` script on the full data set, which is available [here](https://opendata.arcgis.com/datasets/ffc3ef46614d4a7987ef122c53fd621e_6.zip
).

```
a <- read_weighting_area()
nrow(a)
>2838
```

**Comment by rafapereirabr** [comment]
Oi @babisan08 Barbara, voce pode preparar um novo prep para Areas de ponderacao usando esse arquivo acima?

**Comment by babisan08** [comment]
Ok

**Comment by rafapereirabr** [comment]
Oi Barbara. Alguma atualizacao?

**Comment by babisan08** [comment]
Ainda não.

Em ter, 4 de ago de 2020 22:25, Rafael H M Pereira <notifications@github.com>
escreveu:

**Comment by rafapereirabr** [comment]
Alguma atualizacao?

**Comment by babisan08** [comment]
Comecei, dei uma pausa e vou voltar pra ela. Mando em breve.

**Comment by rafapereirabr** [comment]
Barbara, eu nao consegui reproduzir o prep. Na atual versão ele não está baixando os dados originais do IBGE do endereço correto que eu indiquei acima
