### ISSUE TITLE
Create vignettes

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#18]
Create one or two vignettes demonstrating the package functions

**Comment by igorfnasc** [comment]
@rafapereirabr,

Vignette iniciado. Acredito que esse seja suficiente. Seria interessante marcarmos uma reunião rápida para alinharmos o que esperamos do vignette. Vejo possibilidade para um artigo no R Journal.

**Comment by rafapereirabr** [comment]
Sugestão. Para ilustrar como usar o pacote com outros dados:

1. fazer um download de uma tabela do [Atlas to Desenvolvimento Humano](http://atlasbrasil.org.br/2013/pt/download/) e escolher uma variável específica (expectativa de vida, ou mortalidade infantil por exemplo, 
2.  fazer `left_join` dos dados ao mapa `sf`, e 
3.  plotar figura com `ggplot() + geom_sf()`

**Comment by rafapereirabr** [comment]
[Aqui um exemplo bacana de  vignette](https://walkerke.github.io/tidycensus/articles/spatial-data.html).

**Comment by igorfnasc** [comment]
@rafapereirabr ,

O vignette que você sugeriu como modelo mostra apenas os gráficos via ggplot. Mantive as análises estatística com o modelo GWR, reforçando que introduzir as variáveis geográficas pode contribuir para melhorar a especificação do modelo e não "desperdiçar" informação.  É isso ou eu devo voltar apenas para gerar gráficos?

**Comment by rafapereirabr** [comment]
Acho que vale a pena ter (1) uma vignette tipo `basic usage` para mostrar como se carrega os dados  e se faz mapas coropleticos simples usando ggplot2,  e (2) outra vignette para `advanced usage` mostrando a como usar esse dados em análises de regressão espacial e porque isso importa. O (1) é coisa mais curta e simples, mas provavelmente o artigo do journal vai ter que incluir as duas coisas neh.

**Comment by rafapereirabr** [comment]
Eu escrevi uma intro ao pacote que pode servir de base para fazer a vignette de introdução ao pacote: [aqui](https://gist.github.com/rafapereirabr/99c9a2d2aecae87219c459965c75b155)

**Comment by rafapereirabr** [comment]
Se a ideia for escrever um artigo para o R Journal, [esse pacote/artigo serve de otima inspitação](https://journal.r-project.org/archive/2016/RJ-2016-043/index.html).

**Comment by rafapereirabr** [comment]
Igor, eu tentei fazer o knit da `Basic usage` mas deu um erro. O R não encontrou o endereço 
`C:\\Users\\Igor\\Documents\\geo_add\\atlas2013_dadosbrutos_pt.xlsx`. Eu sugiro voce incliur o endreço na web de uma tabela de dados direto do site do projeto atlas

**Comment by rafapereirabr** [comment]
Sugiro usar uma das estratégias abaixo:


```
#temp file
tempf <- file.path(tempdir(), "/atlas.xlsx")

# download
httr::GET(url="http://atlasbrasil.org.br/2013/data/rawData/DADOS_DO_ATLAS_DESAGREGADOS_POR_COR__SEXO_E_DOMICILIO_-_2000_E_2010_-_FINAL.xlsx", httr::write_disk(tempf, overwrite = T))

# read data
adh <- read_excel(tempf, sheet = "MUN 91-00-10")
```

ou 
```
# Download data from the Atlas of Human Development (Ipea)
  download.file("http://atlasbrasil.org.br/2013/data/rawData/DADOS_DO_ATLAS_DESAGREGADOS_POR_COR__SEXO_E_DOMICILIO_-_2000_E_2010_-_FINAL.xlsx", destfile = "./atlas.xlsx", method= "curl", quiet = FALSE)

adh <- read_excel("./atlas.xlsx", sheet = "MUN 91-00-10")
```

**Comment by igorfnasc** [comment]
Deu certo aí? O erro quando eu havia tentado inicialmente permanece. 

Response [http://atlasbrasil.org.br/2013/data/rawData/atlas2013_dadosbrutos_pt.xlsx]
  Date: 2019-07-05 00:12
  Status: 403
  Content-Type: text/html; charset=iso-8859-1
  Size: 249 B

Estou procurando outras soluções.

**Comment by rafapereirabr** [comment]
Ótimo. Fiz uma revisão geral da vignette de introdução ao pacote.  Eu sugiro lançarmos o pacote no CRAN somente com essa vignette. 

Por agora sugiro mover a vignette de `Georeferencing-gain` para outro branch do repositório, e trazer ela para o main branch quando tivermos artigo em estágio mais avançado. O que acha?
