### ISSUE TITLE
issue with code_muni of Itapipoca/CE

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#186]
Issue request from [Twitter](https://twitter.com/tiagopferraz/status/1307035864367853575):

`Rafael, talvez alguém já tenha avisado antes, mas aqui vai. No shape de 1991, o município de Itapipoca/CE retorna  um código IBGE diferente dos demais. Está vindo 2306045, mas a partir de 2000 vem 2306405. Não sei se é um typo mesmo ou se mudou o código.`

**Comment by rafapereirabr** [comment]
@babisan08 , could please have a look at this?

**Comment by rafapereirabr** [comment]
@babisan08 , any updates on this?

**Comment by rafapereirabr** [comment]
@babisan08 , any updates on this?

**Comment by babisan08** [comment]
Sim. O código estava com alguns problemas que estavam impedindo de rodar o código completo, não estava descompactando as pastas entre outros detalhes. Esse primeiro problema já foi resolvido. Sobre o problema do código do município, 1872 está com 4 códigos associados a nomes errados e eu estou trabalhando na solução desse problema. O município de Itapipoca apresenta grafias diferentes em alguns anos e o código está errado na base do IBGE entre 1872 e 1991. Acredito que hoje no final do dia ou no máximo amanhã o prep estará atualizado e com todos os problemas encontrados, solucionados.

**Comment by rafapereirabr** [comment]
Ok. O que voce quer dizer com "1872 está com 4 códigos associados a nomes errados" ?

**Comment by babisan08** [comment]
Itapipoca aparece com o código 2306045 entre 1900 e 1991. Em 1872, não aparece Itapipoca, mas aparece o código do município. O que aconteceu é que na base de 1872, os municípios de Itapipoca, Martins e União dos Palmares receberam o nome de Imperatriz (corrigindo, na verdade são 3 códigos associados a nomes errados).

**Comment by CaioNG** [comment]
Correções implementadas.

**Comment by rafapereirabr** [comment]
Obrigado Barbara e Cario !
