### ISSUE TITLE
Pernambuco state name incorrectly written in grid_state_correspondence_table

### ISSUE THREAD

**Issue by josehcms** [ipeaGIT/geobr#187]
Pernambuco is written 'Pernanbuco' in the data file grid_state_correspondence_table.

code: 
geobr::grid_state_correspondence_table %>% setDT %>% .[ code_state == 'PE',.(name_uf,code_state)] %>% unique

**Comment by rafapereirabr** [comment]
Thank you for the heads up, Jose. @Alandasilva , could you please fix this?

**Comment by rafapereirabr** [comment]
Hi José. This issue has been solved in the dev version. It will be updated in our next CRAN update soon.

```
  utils::remove.packages('geobr')
  devtools::install_github("ipeaGIT/geobr", subdir = "r-package")
  library(geobr)
```

**Comment by josehcms** [comment]
Thank you Raphael!
Great job of you guys with this package!
