### ISSUE TITLE
issue with pytest - read_weighting_area.py

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#188]
Hi @BAFurtado . I've recently updated the data set used in `read_weighting_area` and it seems this has broken the pytest . Could you please have a look at this?

**Comment by rafapereirabr** [comment]
Oops; The error was is a column name in the `weighting_area` data set. I have fixed it now with commit [74d3912](https://github.com/ipeaGIT/geobr/commit/74d391262667c5daa23842fb23e238bbcfa0f089)

**Comment by BAFurtado** [comment]
Hehehe, great. Glad I could be of help... :)
