### ISSUE TITLE
Searching for a city spatial dataframe

### ISSUE THREAD

**Issue by ksw9** [ipeaGIT/geobr#197]
Hi,

Thank you for a wonderful resource! I had a quick question about finding the spatial dataframe for the city of Dourados in Mato Grosso do Sul state. For the city of Campo Grande, I was able to use the following: 
```
nei <- read_neighborhood(2010)
nei_cg <- subset(nei, name_muni=='Campo Grande')
```
However, I wasn't able to do this for Dourados. I'm wondering if there's another function I should be using to access city polygons? 

Thank you so much in advance!
Best,

**Comment by rafapereirabr** [comment]
Hi Katie. Apologies for my late response. Unfortunately, IBGE only makes the neighborhood info for some cities. Hopefully the number of cities with this info will increase with the next population census.
