### ISSUE TITLE
Priority datasets for contributors to work on?

### ISSUE THREAD

**Issue by embruna** [ipeaGIT/geobr#198]
My students and I are interested in contributing some datasets. Are there any that are priorities for inclusion that we could contribute? We were reviewing the [list of datasets available at IBGE](ibge.gov.br/en/statistics/downloads-statistics.html) and there are plenty of options, but would prefer to put our efforts towards something that would be most useful to you (either from IBGE or elsewhere). Thanks very much.

**Comment by rafapereirabr** [comment]
Hi Emilio. Thank you for your interest in contributing to geobr! You might want to have this [contribution guideline](https://github.com/ipeaGIT/geobr/blob/master/CONTRIBUTING.md).

Regarding data sets, we have a few [open issues with data requests](https://github.com/ipeaGIT/geobr/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+Data+request%22). Perhaps you'll be particularly interested on issue #88 . 

In this link below there are other data set related to infrasctrucutre, includig airports, railrods, highways, rivers waterways, etc.
ftp://geoftp.ibge.gov.br/organizacao_do_territorio/redes_e_fluxos_geograficos/logistica_dos_transportes

What data sets would you more interested in contributing with?

**Comment by rafapereirabr** [comment]
Closing this issue for now due to inactivity.
