### ISSUE TITLE
Data update: census tracts 2020 

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#202]
> O IBGE divulga hoje (25) a Malha Setorial Intermediária 2020 em formato digital, com a classificação de setores censitários em urbano ou rural, a fim de atender demandas de planejamento territorial. Ao todo, são 448.988 setores censitários, sendo 344.142 urbanos e 104.846 rurais, que representam a menor porção territorial utilizada pelo IBGE para planejar e realizar pesquisas.
Link: [https://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/30116-ibge-divulga-malha-setorial-intermediaria-2020](https://agenciadenoticias.ibge.gov.br/agencia-sala-de-imprensa/2013-agencia-de-noticias/releases/30116-ibge-divulga-malha-setorial-intermediaria-2020)

**Comment by rafapereirabr** [comment]
Aqui tem o link FTP para a malha de 2019 e de 2020: https://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_de_setores_censitarios__divisoes_intramunicipais/

**Comment by babisan08** [comment]
Ok

**Comment by rafapereirabr** [comment]
@babisan08 , alguma atualização ?

**Comment by babisan08** [comment]
Ainda não.
