### ISSUE TITLE
read_uf ou read_state

### ISSUE THREAD

**Issue by hhmacedo** [ipeaGIT/geobr#22]
O [manual.pdf](https://github.com/ipeaGIT/geobr/blob/master/manual.pdf) diz _read_uf_, mas no pacote a função que faz tal operação parece ser a _read_state_.

**Comment by rafapereirabr** [comment]
Oi Hugo. A função é `red_state` mesmo. Isso é uma confusão da documentação depois que mudamos o nome da função, mas isso será resolvido automaticamente quando atualizarmos a documentação nos próximos dias. Obrigado pelo heads up!
