### ISSUE TITLE
geobr error: object 'geo' not found

### ISSUE THREAD

**Issue by rbenzeev** [ipeaGIT/geobr#220]
Hi, 

I use your package daily for my research. But, now I receive the error below when running any function to import geospatial data. I tried uninstalling and then reinstalling the package but this did not help. See the screenshot below. Please let me know what I can do as soon as possible since I have been reliant on this package for a publication. 

Best,

Rayna

<img width="634" alt="Screen Shot 2021-03-15 at 8 09 33 PM" src="https://user-images.githubusercontent.com/16204003/111245510-5de35680-85ca-11eb-89c5-b326c5c90e70.png">

**Comment by rafapereirabr** [comment]
Hi @rbenzeev . Thank you for the heads up. It seems our server was down for a couple of hours, but is now back. Please try it again and let me know if you have any further issues.
