### ISSUE TITLE
Python: improve error message where there is a connection problem

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#222]
improve error message where there is an internet connection problem. [The current ERROR message in the Python version of geobr is not informative.](https://github.com/ipeaGIT/geobr/issues/221). We should probably use a similar Error message as the one used in the `R` version of `geobr`:

> Error in download_metadata() : 
>   Internet connection problem. If this is not a connection problem in your network, please try geobr again in a few minutes.

**Comment by JoaoCarabetta** [comment]
solved!

**Comment by rafapereirabr** [comment]
Thanks!
