### ISSUE TITLE
Python security issues

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#223]
Hi @JoaoCarabetta . Github is alerting us about [two security issues in the Python package](https://github.com/ipeaGIT/geobr/security/dependabot). Could please have a look into this?

**Comment by JoaoCarabetta** [comment]
The link is broken :/

**Comment by rafapereirabr** [comment]
There are the tlinks to the two issue. [jinja2 ](https://github.com/ipeaGIT/geobr/security/dependabot/python-package/requirements-dev.txt/jinja2/open) and [jinja2 ](https://github.com/ipeaGIT/geobr/security/dependabot/python-package/requirements.txt/jinja2/open). The links work for me. Let me know if you have any problem with them.

**Comment by JoaoCarabetta** [comment]
Maybe they don't work b/c I am not an admin

**Comment by rafapereirabr** [comment]
Ok, I've just changed your status to admin so you can see it now.

**Comment by JoaoCarabetta** [comment]
Fixed

**Comment by rafapereirabr** [comment]
Thanks!
