### ISSUE TITLE
gpkg corrupted?

### ISSUE THREAD

**Issue by NilsDroste** [ipeaGIT/geobr#224]
currently, there seems to be an issue with the one of the downloaded gpkg as `geobr::read_municipality()` fails to read.

Steps to reproduce:

`muns <- geobr::read_municipality(code_muni="all", simplified = F, year=2020)`

Error: Cannot open "..\Temp\RtmpsBQxDW\21MU.gpkg"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.

`sf::st_drivers()` does indicate the existence of a corresponding driver

```
                         name                                                   long_name write  copy is_raster is_vector   vsi
GPKG                     GPKG                                                  GeoPackage  TRUE  TRUE      TRUE      TRUE  TRUE
```

```
sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_Sweden.1252  LC_CTYPE=English_Sweden.1252    LC_MONETARY=English_Sweden.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] sf_0.9-8         ggpubr_0.4.0     eventStudy_0.1.0 here_1.0.1       forcats_0.5.1    stringr_1.4.0    dplyr_1.0.5     
 [8] purrr_0.3.4      readr_1.4.0      tidyr_1.1.3      tibble_3.1.0     ggplot2_3.3.3    tidyverse_1.3.0 
```

**Comment by rafapereirabr** [comment]
Hi @NilsDroste. I believe our server is a bit unstable at the moment. Could you please restart you R session and try it again in an hour or so?

**Comment by henrique1008** [comment]
Hi @rafapereirabr , I have the same problem reported by NilsDroste

**Comment by rafapereirabr** [comment]
Thank you for your suggesiton, @henrique1008. This might help, but it does not entirely solve the problem, which seems to involve making changes to Ipea's server infrastructure. I'm checking this with our IT team. I'll keep you posted here.

**Comment by rafapereirabr** [comment]
Hi all. We've mande some changes to our servers and this problem seems to be fixed now. Thank you for the heads up! Closing this issue for now, but please let us know if you encounter this problem again.

**Comment by rzendonadi** [comment]
Hey team, I've been receiving the message: " '**temp.gpkg' not recognized as a supported file format**" when using the following code: `census = read_census_tract(code_tract="all", year=2020)`. Am I missing something?

**Comment by rafapereirabr** [comment]
Hi @rzendonadi . It seems be working fine on the other machines I've tried on now. Please restart your R session and try again. Let me know if it works

**Comment by rzendonadi** [comment]
Hey, @rafapereirabr. Apparently only for the state of Amapá returns that message when using this **python** code: `geobr.read_census_tract(code_tract = 'AP', year=2020, zone="urban")`. All the other states that I've tried are running well. Can you double check, please?

**Comment by rafapereirabr** [comment]
I just checked and the data file itself is fine. Could you try the code without the `zone="urban"` bit? This parameter is only really necessary when `year=2000`.

`geobr.read_census_tract(code_tract = 'AP', year=2020)`

**Comment by matheushenriquebarboza** [comment]
Estou tendo o mesmo problema aqui, como mostra a figura seguinte. Tentei rodar algumas vezes 3 dias atrás e agora mais algumas vezes, em outro computador, dando sempre esse mesmo problema. Até tentei mudar o ano do layer, mas não adiantou
![image](https://github.com/ipeaGIT/geobr/assets/35461285/33ab5ce3-207a-4da0-a818-04fddd3e438f)

**Comment by rafapereirabr** [comment]
Oi @matheushenriquebarboza . O codigo roda normalmente aqui. Isso pode ocorrer se houve algum problema de conexão durante o download e o arquivo baixado ficou corrompido. Nesse caso, sugiro reiniciar a sessão do R e tentar o download novamente.

```
df <- geobr::read_census_tract(code_tract = 3550308, year = 2000)
head(df)
```
