### ISSUE TITLE
Fiona error? (DriverError: 'temp.gpkg' not recognized as a supported file format.)

### ISSUE THREAD

**Issue by chlavieri** [ipeaGIT/geobr#227]
I tried using the geobr package today in Python 3.8.5 (used it yesterday, it was fine) and it gave me the error in the title when using the function geobr.read_municipality(code_muni="all", year=2019).  Is this a problem in the IPEA server, in a recent commit or in my computer?

**Comment by rafapereirabr** [comment]
Hi @chlavieri . This is a problem in our server we're trying to fix. This issue is being addressed on #224. I'm closing this one here and we can follow up the conversation there.
