### ISSUE TITLE
Corrigir nome de colunas na base de area de ponderação

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#23]
Paulo, alterar o nome das colunas para seguir padrão do pacote. Isso precisa ser alterado tanto no script da função quanto na base de dados 

nome das cols atualmente: `cod_areapond`, `cod_mum`, `cod_uf`

como deve ficar: `code_weighting_area`, `code_muni`, `code_state`

**Comment by rafapereirabr** [comment]
Basta 

1. substituir `cod_` por `code_` no arquivo `prep_weighting_area.R`, e
2. Salvar os dados novamente na pasta do storage3

**Comment by Pauloaraujoo** [comment]
Pronto.

**Comment by rafapereirabr** [comment]
Valeu. Acho que voce esqueceu de atualizara os dados no `storate3`. Eu rodei esse código abaixo e os nomes das colunas ainda estão como `cod_weighting_area cod_muni cod_state`.

```
library(geobr)
 w1 <- read_weighting_area(code_weighting=33)
head(w1)
```
