### ISSUE TITLE
change package title

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#233]
change package title:

from "Loads Shapefiles of Official Spatial Data Sets of Brazil"
to: **"Download Official Spatial Data Sets of Brazil"**

@JoaoCarabetta . Changing the package title in python is not a problem. Is it?

**Comment by JoaoCarabetta** [comment]
Changed, next release will have the new title.

**Comment by rafapereirabr** [comment]
Thanks! BTW, I've recently added a few new data sets/functions. I guess we should start considering a new package update.
