### ISSUE TITLE
Error downloading census tracts

### ISSUE THREAD

**Issue by sachasiani** [ipeaGIT/geobr#239]
I am trying to get the 2010 census tracts for some states. Some of the states are returning an error. I am running the following code:

```
library(tidyverse)
library(readr)
library(sf)
library(geobr)

state_i <- 52
tracts <- read_census_tract(code_tract = state_i, 
                               year = 2010,
                               simplified = F)
```

The error suggests that the downloaded file is corupted 

> Error: Cannot open "C:\Users\Siani\AppData\Local\Temp\RtmpczgG43\53census_tract_2010.gpkg"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.

Obrigado,

-Sacha

**Comment by rafapereirabr** [comment]
Dear  Sacha, we were having some stability issues with our servers earlier today, but things are back to normal now. Could you please restart your R session and run the code again?

**Comment by sachasiani** [comment]
It works. Thanks a lot, Rafael!
