### ISSUE TITLE
Usar base de dados local em read_municipality quando year=2010

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#24]
para carregar base, basta rodar `data("brazil_2010")` e retornar a `return(brazil_2010)`

**Comment by rafapereirabr** [comment]
Oi @rodrigoarruda14 . Eu comecei uma proposta de alteração dessa função, que inclui no script `read_municipality_local.R`. Acho que voce pode continuar a partir de onde parei. Espero que ajude

**Comment by rodrigoarruda14** [comment]
Oi, Rafael,

Dei uma olhada na função e a principio me parece que ela tá funcionando
dessa maneira já (não consigo rodar ela aqui). Eu só incluiria uma condição
no primeiro if: if(year==2010 | !(year %in% ('lista dos anos disponíveis'))
Que seria pra carregar a base toda no caso do ano ser informado inválido.

Você acha que precisa de alguma outra mudança?

ABS,
Rodrigo

Em dom, 16 de jun de 2019 10:20, Rafael H M Pereira <
notifications@github.com> escreveu:

**Comment by rafapereirabr** [comment]
Acho melhor a função retornar um `error` quando a pessoa informar um ano nao existente mesmo.

**Comment by rafapereirabr** [comment]
Fiz uma correções agora, e a função está quase pronta. Mas nao sei porque, o primeiro `if` não aceita duas condições, como abaixo. 
`if (  is.null(year) | year==2010 ){...}`

Se deixo essa linha da função assim acima e não passo argumento algum para `year` (tipo `read_muni(code_muni=11)` ),  dá um erro.

`>Error in if (is.null(year) | year == 2010) { : argument is of length zero`
