### ISSUE TITLE
Adjustment on README.md

### ISSUE THREAD

**Issue by ruanstaffuzza** [ipeaGIT/geobr#240]
Sugiro uma alteração no arquivo README.md para melhor descrever a função lookup_muni. 

A descrição dá a entender que seria uma tabela pra quem quer resolver problema com nomes. Só descobri que ela possui a informação dos códigos de mesorregião olhando os issues. 

Actual version: "Look up municipality codes by their name, or the other way around"

Suggestion1: "Dictionary of municipality code, names, and regions." 
Suggestion2: "Look up municipality code, their name and their meso, micro, intermediate and immediate regions, by name or code."

**Comment by rafapereirabr** [comment]
Essa aqui é a descrição da função no pacote R. Talvez seja o caso de usar a mesma descrição no Python.

```
#' Look up municipality codes and names
#'
#' @description
#' Input a municipality \strong{name} \emph{or} \strong{code} and get the names
#' and codes of the municipality's corresponding state, meso, micro, intermediate,
#' and immediate regions
#'
```

**Comment by ruanstaffuzza** [comment]
A descrição da função no Python é igual a essa do R, que está ótima. 

Minha sugestão era para alterar o README, mas concordo que o README não necessita ser tão específico. 

Pode ter sido só erro meu de não consultar a documentação direito. Por mim pode fechar o issue.

**Comment by rafapereirabr** [comment]
Ok.
