### ISSUE TITLE
Add capitals

### ISSUE THREAD

**Issue by ibarraespinosa** [ipeaGIT/geobr#243]
Hello!

What about adding capitals?

**Comment by rafapereirabr** [comment]
Hi @ibarraespinosa. A function that returns a `data.frame` with the names and codes of capitals would be a good idea.

**Comment by ibarraespinosa** [comment]
That would be very useful.

Em sáb., 22 de mai. de 2021 às 11:05, Rafael H M Pereira <
***@***.***> escreveu:

**Comment by rafapereirabr** [comment]
Hi all. My question is, should the function return the boundaries of the municipalities as `MULTIPOLYGON` or the the location of municipal seats as `POINT` ?

**Comment by rafapereirabr** [comment]
The dev version of **geobr** in `R` now has a `read_capitals()` function.

This function downloads either a spatial `sf` object with the location of the municipal seats (sede dos municipios) of state capitals, or a `data.frame` with the names of codes of state capitals.


```
# Read spatial data with the  municipal seats of state capitals
capitals_sf <- read_capitals(as_sf = TRUE)

# Read simple data.frame of state capitals
capitals_df <- read_capitals(as_sf = FALSE)

```

**Comment by ibarraespinosa** [comment]
thanks
