### ISSUE TITLE
Error in loadNamespace(x)

### ISSUE THREAD

**Issue by ViniciusSato** [ipeaGIT/geobr#244]
Hello!

I'm trying to replicate de tutorial but I get the following error:
># State of Sergige
> state <- read_state(code_state="SE", year=2018)
**Error in loadNamespace(x) : there is no package called ‘crul’**

I already tried reinstalling all the packages and did not find the answer. Can you help me?
![image](https://user-images.githubusercontent.com/21129900/119546241-16b3d780-bd6a-11eb-91e0-01c5461f9e80.png)

**Comment by rafapereirabr** [comment]
Hi @ViniciusSato . Please restart your R session and install the latest version of `geobr`. If the problem persists, I'd suggest you also install the `crul` package. Let me know if this solves your problem.

**Comment by ViniciusSato** [comment]
I've solved the issue after the installation of the dependencies of dplyr

> install.packages("dplyr", dependencies = TRUE)

Thanks! (;
