### ISSUE TITLE
Pré-carregar parte dos dados na pasta /data

### ISSUE THREAD

**Issue by rfdornelles** [ipeaGIT/geobr#245]
Pessoal, 

Espero que estejam bem!

Tendo em vista que por vezes há problemas de conexão pergunto se não seria uma boa já deixar pré-carregado ao menos parte dos dados na pasta /data, de modo que possam ser acessados direto no pacote em caso de instabilidade. Ou, ainda, disponibilizá-los aqui no repositório do projeto para ser lido em caso de instabilidade de conexão.

Muito obrigado pelo pacote, é muito útil!

**Comment by JoaoCarabetta** [comment]
Esse tema foi discutido recentemente aqui:
https://github.com/ipeaGIT/geobr/issues/228

Os dados são mto grandes pra carregar eles no pacote. Pelo menos no CRAN.

Existe a possiblidade de abrir um repo só com a cópia dos dados. Mas, isso criaria mais custos de manutenção para @rafapereirabr e equipe. Também, me parece que o servidor do IPEA está ficando cada vez mais estável.
