### ISSUE TITLE
Typo causing "Error in loadNamespace(name) : there is no package called ‘crul’"

### ISSUE THREAD

**Issue by gbrlambais** [ipeaGIT/geobr#253]
Line 277 of utils.R and line 34 of DESCRIPTION should spell "curl" not "crul".

**Comment by gbrlambais** [comment]
There is something else going on, when I fix the typo I get "Error: 'ok' is not an exported object from 'namespace:curl'"

**Comment by rafapereirabr** [comment]
Thank you, but we actually use a package named `crul`.

**Comment by gbrlambais** [comment]
Thanks, installed crul and now it's working. Should be good to install crul as a dependency then.

**Comment by rafapereirabr** [comment]
Thanks. I've just added `crul` as a package dependency
