### ISSUE TITLE
there is no package called ‘crul’

### ISSUE THREAD

**Issue by romulocenci** [ipeaGIT/geobr#254]
Estou iniciando meus mapas e plots e simplesmente nenhuma função funciona no RStudio no pacote geobr, os comandos listados abaixo dão a seguinte mensagem de erro "there is no package called ‘crul’", acredito ser um typing error:

state <- read_state(code_state="SE", year=2018)
muni <- read_municipality( code_muni = 3550308, year=2010 )
muni <- read_municipality(code_muni= "AL", year=2007)
cntr <- read_census_tract(code_tract = "RJ", year = 2010)
meso <- read_intermediate_region(year=2017)
states <- read_state(year=2019)

Esses comandos estão em um post "https://adrianofigueiredo.netlify.app/post/mapas-em-r-com-geobr/" para aprendizagem do pacote, tentei instalar o devtools e outro pacote "curl", mas o "crul" não existe, alguma resolução?

**Comment by rafapereirabr** [comment]
Oi @romulocenci . Você precisa instalar o pacote `crul` que está [no CRAN](https://cran.r-project.org/web/packages/crul/index.html). Esse problem já será resolvido na próxima versão do geobr.

**Comment by romulocenci** [comment]
Faz pouco tempo que consegui resolver depois de tentar executar o comando de instalação do pacote, depois de umas 3 vezes, obrigado pela resposta
