### ISSUE TITLE
Typo in package definitions ?

### ISSUE THREAD

**Issue by Paul-Mee** [ipeaGIT/geobr#255]
When running this code read_municipality(code_muni=1200179, year=2017)
I get the following error
Error in loadNamespace(x) : there is no package called ‘crul’

I assume that "crul" has been entered instead of "curl" in the code.

Cheers

Paul

**Comment by rafapereirabr** [comment]
Hi Paul. Thanks for the heads up. We actually use a package named `crul`. If you install `crul` on your machine the issue will be fixed.

I have added `crul` as a package dependecy to geobr, so this issue will be fixed for good on our next CRAN update.

**Comment by Paul-Mee** [comment]
Thanks for the quick response

**Comment by rafapereirabr** [comment]
This issue is now fixed with the new version of geobr v1.6.2 on CRAN
