### ISSUE TITLE
Error in read_* functions after timeout

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/geobr#259]
```r
city_shape <- geobr::read_municipality(city_code)
#> Timeout was reached: [www.ipea.gov.br] Connection timed out after 10000 milliseconds
#> Problem connecting to data server. Please try geobr again in a few minutes.
#> Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
#>   Timeout was reached: [www.ipea.gov.br] Operation timed out after 10000 milliseconds with 0 out of 0 bytes received
city_shape <- geobr::read_municipality(city_code)
#> Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
#>   no lines available in input
geobr::read_amazon()
#> Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
#>   no lines available in input
```

Probably related to the metadata file.

**Comment by dhersz** [comment]
My problem with this error is that it's not clear in what is the problem.

Perhaps when reading the metadata file you could use `tryCatch()` to check for any errors (or more specifically, this error). In case of error you delete the metadata file and proceed with the usual process (download metadata file to later download the dataset). If the server is still unstable, you'll get the previous (and clearer) error message, regarding timeout.

**Comment by rafapereirabr** [comment]
oh well, I just got a message from CRAN saying that `geobr` is not "falling gracefully" . This needs to be fixed before Jan 8th

**Comment by rafapereirabr** [comment]
related SO question with promising solution. [https://stackoverflow.com/questions/12193779/how-to-write-trycatch-in-r](https://stackoverflow.com/questions/12193779/how-to-write-trycatch-in-r)

**Comment by rafapereirabr** [comment]
I have wrapped all `httr::GET(..)` calls to download files with `try( ..., silent = TRUE)`
