### ISSUE TITLE
what are "immediate" and "intermediate" regions?

### ISSUE THREAD

**Issue by schmert** [ipeaGIT/geobr#263]
Not a technical comment, but I'm confused by these names. Are these new IBGE geographies, or are they just translated names for old ones? "Immediate", in particular, is not an adjective that one would use in English to describe a region.

**Comment by rafapereirabr** [comment]
Hi Carl. That's a fair question. [In 2017, IBGE created the new "regiões imediatas" and "regiões intermediárias"](https://www.ibge.gov.br/apps/regioes_geograficas/). The idea of this regionalization scheme is to identify the municipalities that are under 'immediate' (closer and stronger) economic influence of Brazil's most important municipalities. The intermediate regions include other municipalities a bit further way but still under the economic influence of a reference city.

Creating the **geobr** package in English allows us to make the data available to a broader international audience, but inevitably some things get lost in translation
