### ISSUE TITLE
ShapelyDeprecationWarning: multi-part geometries is deprecated

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#271]
New issue since multi-part geometries is deprecated in the shapely library. Thanks @luiz-dejesus for pointing this out on issue #269.

```Python

from geobr import read_municipality
mun = read_municipality(year=2017, code_muni = 1200179)

```

> ShapelyDeprecationWarning: __len__ for multi-part geometries is deprecated and will be removed in Shapely 2.0. Check the length of the geoms property instead to get the number of parts of a multi-part geometry.

**Comment by JoaoCarabetta** [comment]
I couldn't reproduce the warning.

My current `shapely` version is `1.8.0` which is the latest.

**Comment by luiz-dejesus** [comment]
Mine too. it's more like a warning for a potential further release from 'shapely'

`shapely                   1.8.0           py310h94bff20_4    conda-forge`

**Comment by rafapereirabr** [comment]
Closing this issue then. Happy to reopen it if someone comes across with this problem again
