### ISSUE TITLE
Server Offline

### ISSUE THREAD

**Issue by augustogeog** [ipeaGIT/geobr#277]
The server is offline, so the package is not working.

Even trying to download geopackages via browser return connection problems. For instance, https://www.ipea.gov.br/geobr/data_gpkg/amc/1920/AMC_1920_1940.gpkg returns a connection error.

Via geobr Python package, the error returned is URLError: <urlopen error [WinError 10060] Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu>"

**Comment by rafapereirabr** [comment]
Oi Augusto. Os servidores do Ipea ainda estão instáveis. Isso tem afeta varios serviços e suportes do TI do Ipea como um todo. Estamos aguardando a TI reestabelecer os servidores. Enquanto isso, estamo tambem avaliando a migração dos dados para um outro servidor mais estável.

**Comment by augustogeog** [comment]
Obrigado!
