### ISSUE TITLE
Names of AMCs

### ISSUE THREAD

**Issue by augustogeog** [ipeaGIT/geobr#278]
The geopackage that is downloaded by calling the read_comparable_areas function comes with the following columns: code_amc, list_code_muni_2010, list_name_muni_2010, geometry. However, AMCs were given names and can be found in other IPEA's systems. Working without names compromises analysis, when we need to check the behavior of specific areas, like the AMC of São Paulo, for instance. Thus, I ask the developers to consider inserting the AMC's names into the database.

**Comment by rafapereirabr** [comment]
Hi @augustogeog. As mentioned in the documentation of the  `read_comparable_areas()` function, this AMC data was created using the methodology poposed by Philipp Ehrl on this [paper](https://www.scielo.br/j/ee/a/d87GfsmvZGhsjTQPLpb8hBJ/?lang=en). In this data set, AMCs hav no names and they are identified by the `code_amc` column.

So it's important to clarify that the AMCs provided in **geobr** do not follow the same methodology of the AMCs you may find on IpeaGeo or IpeaData. Perhaps this is something that should be emphasized on the documentation of the `read_comparable_areas()` function.
