### ISSUE TITLE
Add function `read_country`

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#28]
Adicionar função `read_country`. Que envolve 

```
# 1 carregar dados dos estados
read_state(cod_state="all")
# Dar merge nos poligonos. Um das funções abaixo:
st_union 

 st_combine
```

**Comment by guiducar** [comment]
Oi Rafael, como a função _read_state_  (e todas as outras) já carrega todos os estados se lhe atribuirmos o parâmetro _all_ (como você já disse), eu não entendi o que a função _read_country_ fará, não percebi a diferença entre esta e as outras funções quando especificamos _all_. Pode detalhar melhor, por favor?

**Comment by rafapereirabr** [comment]
A ideia da função é carregar um shape file com o perímetro do país. 

O jeito mais eficiente de fazer isso seria fazer download dos dados de todos estados e depois dissolver as fronteiras entre estados 

Rafael H.M. Pereira

**Comment by guiducar** [comment]
Fazendo o download de todos os estados, e depois dissolvendo as fronteiras, estava demorando muito tempo (coisa de vários minutos). No FTP do IBGE existe o [shape do Brasil](ftp://geoftp.ibge.gov.br/organizacao%5Fdo%5Fterritorio/malhas%5Fterritoriais/malhas%5Fmunicipais/municipio%5F2018/Brasil/BR/), creio que seja mais eficiente remover as fronteiras carregando um shape de uma vez. Um problema que eu encontrei (e que ainda não achei a solução) foi que o mapa (após utilizar a função _st_union_ ), ainda fica com algumas linhas, conforme abaixo (mapa gerado pelo _mapview_):
![Rplot01](https://user-images.githubusercontent.com/49460547/60108370-df33ef00-973e-11e9-83db-e0df3dcfac29.png)

**Comment by guiducar** [comment]
Usando o shape do Brasil de 2018 o problema foi resolvido!

**Comment by rafapereirabr** [comment]
Eh, o `st_union` nao funciona muito bem ainda.  Acho que a sua sugestao vai ser mais facil e rapida de implementar mesmo

**Comment by guiducar** [comment]
Eu acabei fazendo da forma que você disse. O st_union não funciona bem nos anos: 2000, 2001, 2014 e 2015, mesmo se eu usar o shape do Brasil, então a função vai travar ou carregar algumas linhas,  se o usuário especificar qualquer um desses anos.

**Comment by guiducar** [comment]
Não sei se alguém já notou isto, mas a função read_state não funciona se o pacote DataTable estiver carregado. Como a minha função foi escrita editando a read_state, ela está com a mesma incompatibilidade.

**Comment by rafapereirabr** [comment]
> Não sei se alguém já notou isto, mas a função read_state não funciona se o pacote DataTable estiver carregado. Como a minha função foi escrita editando a read_state, ela está com a mesma incompatibilidade.

Resolvi. Era só transformar o metadata.rds para `data.frame` (sem `data.table`)

**Comment by rafapereirabr** [comment]
A operação `st_union` demora muito mesmo. O ideal seri que o usuário não tivesse que rodar ela toda vez que chama a função.
Então eu peguei o seu código e criei um script `prep_country` para gerar os arquivos de `sf` do Brasil pra todos anos e salvar esses dados no nosso servidor.
Agora, quando o usuário chama a função, `read_country`, a função simplesmente faz o download do arquivo que já está pronto.

**Comment by rafapereirabr** [comment]
Função `read_country` já funcionando!
