### ISSUE TITLE
Error to get data

### ISSUE THREAD

**Issue by mdecalves** [ipeaGIT/geobr#281]
Dear respected,
geobr is not working to get data. When using a function read_state, for example, we are getting the following error:

state <- read_state(code_state="SE", year=2018)
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input

Could someone help us solving this problem?
Best regards,
Marcelo

**Comment by rafapereirabr** [comment]
Hi Marcelo. Please restart your R session and check if the problem persists.

**Comment by mdecalves** [comment]
Dear Rafael,
After restarting the function work as well as the read_municipality function.
thank you very much for your prompt response.
All the best,
Marcelo

**Comment by rafapereirabr** [comment]
Great. I'm glad to help.
