### ISSUE TITLE
Typo in column name (lookup_muni) `abrev_state` instead of `abbrev_state`

### ISSUE THREAD

**Issue by GoulartNogueira** [ipeaGIT/geobr#282]
`lookup_muni` has a column named `abrev_state` (single B), while other databases use `abbrev_state` (double B)

```
geobr.lookup_muni().columns.tolist()
>>  ['code_muni',  'name_muni',  'code_state',  'name_state',  'abrev_state', ...

geobr.read_schools(year=2020).columns.tolist()
>> ['abbrev_state', ...
geobr.read_state(year=2020).columns.tolist()
>> ['code_state', 'abbrev_state', ...
geobr.read_municipality(year=2020).columns.tolist()
>> ['code_muni', 'name_muni', 'code_state', 'abbrev_state', ...
```

It might seem a very small (irrelevant) difference, but when merging the DBs together, it's way easier when we have the exact same column name. So I believe it should be fixed (standardized) on further releases.

**Comment by rafapereirabr** [comment]
Hi @GoulartNogueira . Thanks for the heads up. This is a simple fix I can make in the next few days.

**Comment by rafapereirabr** [comment]
Hi André. Sorry for the late response. Thank you for your pull request. Fixing the problem involved making changes to several scripts and updating the data in our server. These fixes have now been implemented in the dev version of geobr
