### ISSUE TITLE
 Installation error in install_github('ipeaGIT/geobr')

### ISSUE THREAD

**Issue by raonigs** [ipeaGIT/geobr#285]
When prompted to install the 'geobr' package by the command:

**_devtools::install_github('ipeaGIT/geobr', subdir = 'r-package')_**

The following error message returns:

![errogeobr](https://user-images.githubusercontent.com/98754863/166155883-8f638608-a20b-44ec-a402-02ae6516178d.png)

And I can't install the package.
How can I proceed with this?

**Comment by rafapereirabr** [comment]
This is strange. Please restart your R session, update `magrittr` and then try installing `geobr` again.

**Comment by rafapereirabr** [comment]
In any case, I just removed `magrittr` from the suggested packages in `DESCRIPTION`. This should solve the problem.
