### ISSUE TITLE
Cannot install geobr via install.packages 

### ISSUE THREAD

**Issue by tp-duarte** [ipeaGIT/geobr#288]
Hi there, 

Trying this code to install geobr in R 

```
install.packages("geobr")
library(geobr)
```
raises me the following error : Warning in install.packages : package ‘geobr’ is not available for this version of R. My RStudio version currently is 4.2.0, but I tried to install geobr via Jupyter with R 3.63 version, and it didn't worked as well. 

When I was looking for the package in R-Cran in this link  https://cran.r-project.org/web/packages/geobr/, it shows the message 

" Package ‘geobr’ was removed from the CRAN repository.

Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/geobr).

Archived on 2022-01-23 for repeated policy violation.

A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2022/2022-01-23_check_results_geobr.html).

Please use the canonical form https://cran.r-project.org/package=geobr to link to this page. "

**Comment by rafapereirabr** [comment]
Hi @tp-duarte , geobr is temporarily not available on CRAN. In the meantime, you can install the development version with latest features available from github.

Installing the dev version:
```
  devtools::install_github("ipeaGIT/geobr", subdir = "r-package")
  library(geobr)

```
