### ISSUE TITLE
add UF, or name UF to municipality dataset

### ISSUE THREAD

**Issue by lucasmation** [ipeaGIT/geobr#29]
e ai @rafapereirabr ! Ta ficando legal!!

Minor suggestion: add UF name to municipalities dataset. 

Sometimes the person will only have UF names and Municipality names (as in my case now with the Brasil Mais Produtivo data). And municipal names are not unique, only within State.

**Comment by rafapereirabr** [comment]
Ok, we'll add UF names and Municipality names as new columns to the municipalities data set

**Comment by rafapereirabr** [comment]
Adding columns `code_state` (numeric) and `abbrev_state` (two-letter abbreviation of state)
