### ISSUE TITLE
[dúvida] adicionar geometrias em uma base do geobr

### ISSUE THREAD

**Issue by filipemsc** [ipeaGIT/geobr#292]
Estou usando a base georreferenciada do CNES do pacote `geobr` para dar merge com uma outra base do Sistema de Saúde. No entanto, a base do CNES no `geobr` está um pouco defasada, e para um número bastante pequeno de estabelecimentos mais recentes não há informações de georreferenciamento disponíveis. Gostaria de adicionar essas informações manualmente, colocando o código do CNES e as coordenadas em uma nova linha. Em especial, estou tentando fazer o seguinte:

``` r
library(geobr)
library(dplyr)

cnes <- read_health_facilities()
#> Using year 2015

cnes %>% select(code_cnes, geom) %>%
  add_row(code_cnes = 0466573, geom = "c(-23.542718314060533,-46.5927947)")
#> Error in `vec_rbind()`:
#> ! Can't combine `..1$geom` <sfc_GEOMETRY> and `..2$geom` <character>.
```
Alguma sugestão de como poderia fazer isso?

PS: Qual seria o melhor local para conseguir as coordenadas com base em endereço (cep+rua+numero) no mesmo sistema de referência que o geobr?

**Comment by rafapereirabr** [comment]
Oi Felipe. Os dados do CNES ques estão no geobr eram baixados do site [http://dados.gov.br/](http://dados.gov.br/), mas o site parou de atualizar os dados, infelizmente. 

Quanto a sua pergunta, minha sugestao é usar o pacote sfheaders para primeiro converter os pontos e coordenadas num `point sf` e depois fazer o rbind.

**Comment by rafapereirabr** [comment]
fechando o issue porque nao se trata exatamente de um problema no geobr.
