### ISSUE TITLE
Como mascarar um estado, a partir de um arquivo netcdf usando o Geobr

### ISSUE THREAD

**Issue by evmpython** [ipeaGIT/geobr#295]
Olá Rafael, tudo bem?

Tenho utilizado o geobr e gostado bastante. Eu tenho um arquivo Netcdf de relâmpagos para o Brasil. Porém eu gostaria de plotar uma figura recortando apenas para o Estado de MG (como exemplo essa figura aqui: https://drive.google.com/file/d/1W72zYSnLIqpeIyoWd-O-vU6Cvob9LjOh/view?usp=sharing), ou seja, mascarar as demais regiões. Geralmente eu uso o shapefiles do Ibge e a biblioteca salem, mas por praticidade gostaria de usar o Geobr. Segue como exemplo meu arquivo netcdf: https://drive.google.com/file/d/1x40kNxHlJVLvuibUSKdVfaNEUVQn5bEp/view?usp=sharing

Desde já muito obrigado.

abraço,
Enrique

**Comment by rafapereirabr** [comment]
Oi Enrique. Sua pergunta é mais relacionada a questões de operação/ manipulação de dados espaciais. Eu sugeriria você dar uma olhada nos pacotes sf, raster, stars etc . Mas como a pergunta não é diretamente relacionada ao geobr, vou vou fechar o issue
