### ISSUE TITLE
Downloading Using install_github

### ISSUE THREAD

**Issue by cherullodc** [ipeaGIT/geobr#296]
I am an RA helping a professor this summer and I need to generate maps of Brazil with climate and agricultural data she has collected. 

I am having trouble downloading the package, as when I use install.packages it says that geobr is not available for the current version of R. I then tried to use install_github, because I saw it was no longer on CRAN, and when I do this it presents me with the option to download what seems like different versions of the package. The output is pasted below: 
> githubinstall("geobr")
Select a number or, hit 0 to cancel. 

 1: 56north/geoDK         Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
 2: CarlBoneri/gendr      Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
 3: Ironholds/zebr        Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
 4: MoBiodiv/mobr         Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
 5: adamdsmith/geobird    Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
 6: ajschumacher/gogr     Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
 7: baddstats/globe       Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
 8: cardiomoon/webr       Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
 9: stephLH/webr          Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
10: csp-inc/geer          Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
11: dgrtwo/ebbr           Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
12: etiennebr/geom        Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
13: gibonet/gibr          Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
14: gndaskalova/grabr     Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
15: willpearse/grabr      Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
16: jpfrench81/gear       Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
17: michaeldorman/geobgu  Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
18: nawendt/gribr         Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo
19: samuel-rosa/febr      Fe-BR: Repositório Brasileiro de Dados de Ferro do Solo

Is this what it is supposed to be doing? And if it is, which one should I choose? 

Thank you for your help, I am new to using these more advanced packages.

**Comment by rafapereirabr** [comment]
To install the dev version of `geobr` from CRAN, you shour run the following code:

```
devtools::install_github("ipeaGIT/geobr", subdir = "r-package")

library(geobr)
```
