### ISSUE TITLE
Macrorregiões de Saúde

### ISSUE THREAD

**Issue by AltairMassaro** [ipeaGIT/geobr#297]
Caros colaboradores,
Inicialmente, gostaria de parabenizar a todos pelo excelente trabalho com este projeto.
Bem, tenho trabalhado com dados em saúde e ao plotar as regiões de saúde, não consigo definir as macrorregiões, como aparece em "read_health_region", por favor, podem me ajudar?
Muito obrigado.
Atenciosamente,
Altair Massaro

**Comment by rafapereirabr** [comment]
Ola @AltairMassaro . Você tentou usar o parametro `macro = TRUE`, como indicado na documentação?

```
df <- read_health_region(year = 2013, macro = TRUE)
```

**Comment by massaro-altair** [comment]
Muitíssimo obrigado. Valeu
Grande abraço
