### ISSUE TITLE
update geopandas (python)

### ISSUE THREAD

**Issue by michelmetran** [ipeaGIT/geobr#302]
Uso a versão para python e notei que o geopandas utilizado no projeto geoBr é a versão 0.7.0.

Visando agregar funções mais recentes, seria interessante se o projeto atualizasse a dependência para a versão mais atual da biblioteca.

Umas das funções que uso muito, do geopandas (e que agregaria muito na visualização dos dados do geoBr), é a `gdf.explore()`. Porém não tem essa função na versão do geopandas 0.7.0.

Estou "atropelando" as dependências, atualizando o geopandas, sem problemas até o momento...
`pip3 install geopandas --upgrade`

Há algum impeditivo conhecido na atualização do geopandas?
... por ora fica a sugestão.

Dei um fork no projeto para estudar como contribuir.
Precisarei estudar gerenciamento de dependências pelo `pyproject.toml`.

**Comment by GitHunter0** [comment]
Hey folks @JoaoCarabetta , @rafapereirabr , any update in here?

It would be good to allow `geopandas` most recent version `0.14`.

**Comment by rafapereirabr** [comment]
Hi both. This looks like a simple fix. Right?

I'm not the geobr Python person (that's @JoaoCarabetta), but I think we could solve this issue by simply update:

 `geopandas==0.14.0` in these files:
- [requirements-dev.txt](https://github.com/ipeaGIT/geobr/blob/master/python-package/requirements-dev.txt)
- [requirements.txt](https://github.com/ipeaGIT/geobr/blob/master/python-package/requirements.txt)


`geopandas=0.14.0=py_0`, in this file
- [conda_requirements.txt](https://github.com/ipeaGIT/geobr/blob/master/python-package/conda_requirements.txt)

and `geopandas = "^0.14.0"` in this file:

- [pyproject.toml](https://github.com/ipeaGIT/geobr/blob/master/python-package/pyproject.toml)


Correct? Or perhaps I'm missing something. Ping to @vss-2

**Comment by GitHunter0** [comment]
@rafapereirabr , folks, with all due respect, but Ipea is a reputed  **Public** institute. If @JoaoCarabetta does not even respond to a simple issue like this after **5 months**, please find another programmer to replace him, it is a disrespect with the people that rely on the work of this institution.

**Comment by JoaoCarabetta** [comment]
Hi @GitHunter0 and @michelmetran, I just updated the packages (PR #341). This should solve all your issues.

@GitHunter0, the python package is maintained by me, for free, in my spare time. You are welcome to contribute to it at any time. It is all open source exactly for this reason.

**Comment by rafapereirabr** [comment]
thanks for the PR @JoaoCarabetta !
