### ISSUE TITLE
Erro utilizando a função read_municipality

### ISSUE THREAD

**Issue by grazLet** [ipeaGIT/geobr#303]
Olá, estou tentando utilizar a função read_municipality do pacote geobr, porém não obtive sucesso nas duas últimas semanas. O seguinte erro surge ao chamar a função: 

_Problem connecting to data server. Please try again in a few minutes._

**Comment by rafapereirabr** [comment]
Por favor, instale a última versão do geobr v1.7.0 e tente novamente

`install.packages("geobr")`

**Comment by grazLet** [comment]
> Por favor, instale a última versão do geobr v1.7.0 e tente novamente
> 
> `install.packages("geobr")`

Olá, eu já estou utilizando a última versão do pacote. Também já desinstalei e instalei novamente, porém o erro permanece.

_> packageVersion("geobr")
[1] ‘1.7.0’_

**Comment by rafapereirabr** [comment]
Hi @grazLet . Could you please try the function again?

**Comment by grazLet** [comment]
> Hi @grazLet . Could you please try the function again?

Olá, tentei utilizar a função novamente e o erro permanece. 

_> all_mun_pr <- read_municipality(code_muni=41, year=2020)
Problem connecting to data server. Please try again in a few minutes_.
_> all_mun_pr <- read_municipality(code_muni=41, year=2019)
Problem connecting to data server. Please try again in a few minutes._

**Comment by rafapereirabr** [comment]
Aqui está funcionando ok. Por favor, reinicie sua sessão de R e tente de novo

**Comment by rafapereirabr** [comment]
Closing this issue for now due to lack of response. I'm glad to reopen the issue if the problem persists
