### ISSUE TITLE
Graus ficam quadrados nos eixos x e y

### ISSUE THREAD

**Issue by barbosawf** [ipeaGIT/geobr#306]
Estou usando a seguinte código:

library(geobr)
library(ggplot2)

MG1 <- read_state(code_state = "MG", year = 2020)

ggplot(MG1) +
  geom_sf()

![image](https://user-images.githubusercontent.com/105462541/211911703-69be0805-5eb4-4e0a-91d7-6d9d12b2b15f.png)

E obtive a seguinte imagem acima. Os graus ficam quadrados nos eixos x e y.

Versão do R é a 4.2.2 e o R studio é o mais recente.

**Comment by rafapereirabr** [comment]
Oi @barbosawf . Obrigado por abrir o issue. Que estranho isso, não sei ainda o que poderia estar causando isso. Mas esse problema só parece ocorrer com a nova versão do R  v4.2.2. O sinal de graus aparece normal em versões anteriores.

**Comment by rafapereirabr** [comment]
O problema acontece em outras bases de dados espaciais, nao apenas com as bases do geobr. Exemplo abaixo. Parece ser mesmo um problema do R 4.2.2. 

```
library(sf)
library(geobr)
library(ggplot2)

nc <- sf::st_read(system.file("shape/nc.shp", package="sf"))


ggplot() +
  geom_sf(data = nc)

```
