### ISSUE TITLE
Suggestion: make code_muni="all" the default (and also for code_uf)

### ISSUE THREAD

**Issue by lucasmation** [ipeaGIT/geobr#31]
personal opinion here: I don't like to have to tell the function which subset of the data I want. The natural expectation is that you will get all the data. Making code_muni="all" the default would avoid this. 

I think having this default at least for the small datasets (mun, uf, micro, macro) makes sense. 

Far large dataset such as setor censitario, faces, etc. than you could force user to define *_muni="all"

**Comment by rafapereirabr** [comment]
Hi Lucas. I appreciate your point. Nonetheless, every time one calls a function, the package will download the data from Ipea's website. If `code_ = "all"` this means downloading even more data. If we leave `code_muni="all"` as the default option, some users might forget to add the `code_` argument and contribute to overloading the website with unnecessary download calls. We think it's better to keep `code_= "all" ` to certify that the user is conscious that she/he wants the data of the whole country.

In any case,  appreciate the point you raised. This is something we could change in the future if more people come up with the same suggestion. I'll close this issue for now.

**Comment by rafapereirabr** [comment]
This has now been solved in the new version v1.2
