### ISSUE TITLE
geobr::read_disaster_risk_area allows only year=2010

### ISSUE THREAD

**Issue by writing-versioncontrol** [ipeaGIT/geobr#325]
R> data = read_disaster_risk_area(year=2003)
Error in select_year_input(temp_meta, y = year) : 
  Error: Invalid Value to argument 'year'. It must be one of the following: 2010
R> data = read_disaster_risk_area(year=2017)
Error in select_year_input(temp_meta, y = year) : 
  Error: Invalid Value to argument 'year'. It must be one of the following: 2010

**Comment by rafapereirabr** [comment]
This dataset is currently only available for 2010. I've made this clearer in the documentation of the dev version.

ps. We will include an uptdated version of the data once it is published.
