### ISSUE TITLE
Municipality years missing from list_geobr return

### ISSUE THREAD

**Issue by fbrustolin** [ipeaGIT/geobr#330]
Despite data for municipalities in 2021 and 2022 being available and correctly informed in the read_municipality error message, those years are absent in the output of list_geobr function.

```
library(geobr)
geobr_datasets = list_geobr()
geobr_datasets$years[geobr_datasets$geography == "Municipality"]
read_municipality(code_muni="all", year=-1)
```

**Comment by rafapereirabr** [comment]
Thanks for the heads up, @fbrustolin. I've open the issue #331 to report the error in `read_municipality(year = 2021, simplified = TRUE)`.

In my next commit, I'm fixing this issue by adding years 2021 and 2022 to the municipality reference in `list_geobr()`
