### ISSUE TITLE
Issue in read_region() : Centro-oeste is empty

### ISSUE THREAD

**Issue by JFARod** [ipeaGIT/geobr#332]
Os dados poligonais da região Centro Oeste estão vazios, o que leva a problemas desse tipo

![image](https://github.com/ipeaGIT/geobr/assets/48330015/c1637387-6d4e-4993-9ac7-8f63eb17863b)

**Comment by rafapereirabr** [comment]
@JFARod , voce poderia por favor colar abaixo o código que voce usou para criar essas imagem ?

**Comment by JFARod** [comment]
> @JFARod , voce poderia por favor colar abaixo o código que voce usou para criar essas imagem ?

Claro @rafapereirabr , aqui está
`library(tidyverse)
library(geobr)

geo_reg<-read_region()

map_br_reg<-resumo_reg%>%
  left_join(geo_reg,by=join_by(NomeRegiao==name_region))%>%
  select(-c(code_region))
ggplot(data=map_br_reg)+
  geom_sf(aes(fill=casos,geometry=geom))+
  labs(title = "Distribuição de Casos no Brasil por Região")`

Também envio a View do objeto para mostrar que a linha Centro-oeste veio vazia
![image](https://github.com/ipeaGIT/geobr/assets/48330015/0e01113d-f8a3-43e1-85b0-7b062697efc5)
