### ISSUE TITLE
Add bank branches database

### ISSUE THREAD

**Issue by BCamina** [ipeaGIT/geobr#34]
Brazilian Central bank updates on a monthly basis a database with addresses of all bank branches in Brazil.

There is a database for branches, PAE, PAB (these two are smaller branches, usually inside large companies) and consórcio administrator.

Link is below

https://www.bcb.gov.br/estabilidadefinanceira/agenciasconsorcio

**Comment by rafapereirabr** [comment]
Thanks Bruno. From what I could briefly see in their data, the have the address of each bank branch. However, the dataset does no bring information on the `lat` `long` coordinates. Correct?

**Comment by BCamina** [comment]
There are no latitude and longitude coordinates. 

When I used this database + IBGE shapefiles in GeoDA I matched them using city and state names (since this base contains BCB code for municipalities, and not IBGE code)

**Comment by rafapereirabr** [comment]
Ideally, it would only make sense to include this database in the package if we had the coordinates. Perhaps we could do the effort to geocode these data here at Ipea, but this would take some time since we have other short-term priorities

**Comment by rafapereirabr** [comment]
temporarily closing this issue for innactivity
