### ISSUE TITLE
Função read_health_region

### ISSUE THREAD

**Issue by helkennedy** [ipeaGIT/geobr#358]
Eu gostaria de acessar um banco de dados com os códigos das regiões de saúde e de seus respectivos municípios. A função read_health_region mostra apenas o código das regiões de saúde. Sabem onde posso conseguir a informação das regiões de saúde e de dos municípios?

**Comment by rafapereirabr** [comment]
voce pode gerar essa info com uma rapida operaçã de interseção espacial. Codigo abaixo:

```
library(geobr)
library(sf)
library(dplyr)

muni_seats <- geobr::read_municipal_seat(year = 2010)

hregions <- geobr::read_health_region(year = 2013, macro = TRUE)


df <- sf::st_join(muni_seats, hregions)

head(df)

  
df <- df |>
  dplyr::select(code_muni, name_muni, code_health_marcroregion, name_health_macroregion)

df

```

**Comment by helkennedy** [comment]
Funcionou. Muito obrigado!

**Comment by rafapereirabr** [comment]
otimo. abs
