### ISSUE TITLE
Wrong weird shape for Barra Do Brugres municipality

### ISSUE THREAD

**Issue by jaum20** [ipeaGIT/geobr#365]
The following code plots the Mato Grosso state and highlits the municipality of Barra Do Bugres.

```
library(geobr)
library(ggplot2)

mt_muni = read_municipality(code_muni = "MT", year= 2022, showProgress = FALSE)

ggplot()+
  geom_sf(data=mt_muni,fill='cornsilk', colour='black') +
  geom_sf(data=mt_muni[mt_muni$name_muni=='Barra Do Bugres',], fill='red', colour=NA)+
  theme_void()
```

But the shape looks wrong, with disconected polygons:

![image](https://github.com/user-attachments/assets/eed9fb77-f67c-4cd1-b07a-5f113173185f)

The municipality boundaries according to [wikipedia](https://upload.wikimedia.org/wikipedia/commons/9/90/MatoGrosso_Municip_BarradoBugres.svg) are different:

![image](https://github.com/user-attachments/assets/5bbe7ffd-2f88-4894-be6e-28cd08779a30)

Is this a bug ?

**Comment by jaum20** [comment]
```
ggplot()+
  geom_sf(data=mt_muni[mt_muni$name_muni=='Barra Do Bugres',], fill='red', colour='black)+
  theme_void()
```

![image](https://github.com/user-attachments/assets/50127a4f-b301-4c88-a492-b9de52c9944f)

**Comment by rafapereirabr** [comment]
Thaks for the heads up! This seems to be an error with IBGE's original data set. Here, have a look at the [2022 shape file](https://geoftp.ibge.gov.br/organizacao_do_territorio/malhas_territoriais/malhas_municipais/municipio_2022/UFs/MT/). The map of Barra do Bugres also looks like this in the original data for other years as well.

**Comment by jaum20** [comment]
Looks like the IBGE map is right. Found this thread at reddit about the municipality. https://www.reddit.com/r/brasilivre/comments/k5uyvu/o_inusitado_mapa_de_barra_do_bugres_mt_uma_cidade/

Thanks for your time. Closing this
