### ISSUE TITLE
Suggest updated of geopandas and shapely dependencies

### ISSUE THREAD

**Issue by robmarkcole** [ipeaGIT/geobr#373]
Running `pip install geobr` results in a pretty ancient version of geopandas being installed. I briefly tested with
```
geopandas==1.0.1
shapely==2.0.6
```
without issue, and suggest upgrading the dependencies

**Comment by rafapereirabr** [comment]
Thanks for the heads up @robmarkcole . Would you like to open a PR with the changes?

**Comment by rafapereirabr** [comment]
closed with PR #374
