### ISSUE TITLE
add function to read municipalities in the 'Legal Amazon'

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#38]
[Link to the list of municipalities in the Legal Amazon](http://geoftp.ibge.gov.br/organizacao_do_territorio/estrutura_territorial/amazonia_legal/)

**Comment by rafapereirabr** [comment]
@pedro-andrade-inpe Pedro, voce sabe onde tem um shape da Amazonia Lega? 
No site do IBGE só tem uma lista de municipios. Na pagina do [INPE tem um arquivo](http://www.dpi.inpe.br/Ambdata/unidades_administrativas.php) e no site do [MMA tambem tem um](http://mapas.mma.gov.br/i3geo/datadownload.htm) mas eles sao diferentes. A opção da lista de municipios nao é idel por conta dos municipios cortados pela zona etc.

**Comment by pedro-andrade-inpe** [comment]
Oi @rafapereirabr, o dado do MMA esta correto, pois segue a definição legal que consta no código florestal (lei 12.651):

Art. 3º Para os efeitos desta Lei, entende-se por:

I - Amazônia Legal: os Estados do Acre, Pará, Amazonas, Roraima, Rondônia, Amapá e Mato Grosso e as regiões situadas ao norte do paralelo 13º S, dos Estados de Tocantins e Goiás, e ao oeste do meridiano de 44º W, do Estado do Maranhão;

O dado do Ambdata possui os estados do Tocantins e Maranhao completos. Segundo a lei, apenas parte deles esta na Amazônia Legal.

**Comment by rafapereirabr** [comment]
ok! Valeu pelo esclarecimento!

**Comment by rafapereirabr** [comment]
new function `read_amazon` added to the package
