### ISSUE TITLE
add function to read municipalities by biome

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [ipeaGIT/geobr#45]
The user could select a given biome (Amazonia, Caatinga, Cerrado, Mata Atlantica, Pampa, Pantanal) and get all municipalities that belong to it, in a way similar to #38 and #39.

**Comment by rafapereirabr** [comment]
I think the preferred approach here would be to implement a function that loads the boundaries of all  biomes, if there is any official shape file with these data. Do you have any info about this? Where we could download these shape files (possible for different years) ?

**Comment by pedro-andrade-inpe** [comment]
http://mapas.mma.gov.br/i3geo/datadownload.htm
in the menu i3geo -> Biomas (MMA/IBGE)
I know that IBGE is working on a new version that will probably be released next month.

**Comment by rafapereirabr** [comment]
Do you know whether the boundaries change in different years ? 

Rafael H.M. Pereira

**Comment by pedro-andrade-inpe** [comment]
I talked to some colleagues about this issue. There is currently no review in the biomes map since its first relase, in 2004 (https://ww2.ibge.gov.br/home/presidencia/noticias/21052004biomashtml.shtm).

**Comment by rafapereirabr** [comment]
Hi Pedro, we've addded the `read_biomes` function. Let me know if you have any thoughts or suggestions on how to improve it.
