### ISSUE TITLE
add Terras Indígenas 

### ISSUE THREAD

**Issue by schmert** [ipeaGIT/geobr#47]
for future consideration:  add a _read_terras_indigenas_ function that grabs polygons from FUNAI

**Comment by rafapereirabr** [comment]
Hi. That’s a good suggestion! Thanks. Do you know a link where one can find the official data with shape files of indigenous reserves in Brazil?

**Comment by schmert** [comment]
I have shapefiles from several years ago, but I'll ask on Twitter about more current versions.

**Comment by schmert** [comment]
I constructed a list of the _setores censitários_ that belong to each _terra_ at https://gitlab.com/schmertmann/indigenous-fertility-brazil/blob/master/Data/setores.indigenas.csv  .  It's a little bit "artesenal", though.

**Comment by schmert** [comment]
http://www.funai.gov.br/index.php/shape  has nice shapefiles, with much-improved UTF-8 encoding 

I did an experiment at https://gitlab.com/schmertmann/indigenous-fertility-brazil/tree/master/Data/shapefiles 

![TI](https://user-images.githubusercontent.com/6287005/61189304-88dd1080-a659-11e9-8421-b2f0eb5745ab.png)
![TI-MS](https://user-images.githubusercontent.com/6287005/61189307-8e3a5b00-a659-11e9-8393-cf05adf256a8.png)

**Comment by rafapereirabr** [comment]
Brilliant! Thanks gCarl. I’m currently on a trip but I can add this data/function to geobr in August. Do you know if the data is available with updates 

Rafael H.M. Pereira

**Comment by rafapereirabr** [comment]
I've just writte the script `./prep_data/prep_indigenous_land.R` to download the data and add it to our repository. Now I only need to write the function `read_indigenous_land.R`

**Comment by schmert** [comment]
_read_indigenous_territory_ sounds more natural in English

**Comment by rafapereirabr** [comment]
Oh, "indigenous land" has more hits on google, so I thought it would sound more natural this way. Thanks for the heads up!

**Comment by schmert** [comment]
That's exactly my algorithm for deciding about Portuguese phrases! :) 

This is not a slam dunk, and maybe you should poll others.  There might be US/British/Canadian/Australian/etc. differences.  To me "territory" connotes a legal definition, while "land" just means a place.  So if you say "Yanomami land" that might mean "places where Yanomami people live, or used to live",  but "Yanomami territory" suggests land that is under Yanomami control.

**Comment by pedro-andrade-inpe** [comment]
The data produced by FUNAI includes indigenous areas in different steps of the homologation process. In the current version of the data, six areas are in the first step, which is called under study ("Em Estudo"). Such areas are more related to the term "land" stated by @schmert. Only in the last steps of the homologation process they can be considered "territory". Additionally, the Brazilian Constitution also uses the term "terras indigenas" (indigenous lands), and not "territorios indigenas" (idigenous territories). Therefore I believe the term "land" is more appropriated to be used in the name of the function.

**Comment by rafapereirabr** [comment]
Thank you for sharing, Pedro.  These are official shape files from FUNAI bringing info on indigenous lands at various stages of demarcation and study. In this sense, I agree it sounds more appropriate to use the broader term 'indigenous lands'. BTW, I've just written a function to download the data. I only need to upload the data to our server and it should be working. I'll keep you updated here

**Comment by rafapereirabr** [comment]
function included and working!
