### ISSUE TITLE
read_municipio: include `cod_uf` argument 

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#5]
Include `cod_uf` argument in the `read_municipio` function

**Example:**
`read_municipio(cod_uf="SP", ano=2010)` returns all municipalities of UF 35

**Comment by rafapereirabr** [comment]
@rodrigoarruda14 , Acho que podemos fechar esse issue, certo ?

**Comment by rodrigoarruda14** [comment]
Pode sim
