### ISSUE TITLE
read_weighting_area retornando "Error in parse_url"

### ISSUE THREAD

**Issue by matth3us** [ipeaGIT/geobr#50]
` test <- read_weighting_area(code_weighting = 35, year=2010)`
`test <- read_weighting_area(code_weighting = "SP", year=2010)`

Os códigos acima retornam "Error in parse_url(url) : length(url) == 1 is not TRUE".

Estou entrando algo errado, ou a função está com problemas?

**Comment by rafapereirabr** [comment]
Oi Matheus. Eu identifiquei aqui um erro na geração do arquivo de endereços dos dados de área de ponderação. Vou corrigir isso e te dou um retorno amanhã

**Comment by rafapereirabr** [comment]
Oi Matheus. Questão resolvida. Obrigado pelo alerta. Era só uma atualização interna do arquivo de endereços. A função já está funcionando. Vou fechar esse issue . qualquer coisa, é só falar aqui pelo git. abs
