### ISSUE TITLE
Urbanized areas

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#52]
1. Create script `prep_urban_areas` do download and clan IBGE data on urbanized areas (years 2005 and 2015)

2. Create `geobr` function `read_urban_area()` to download the data

obs. data available at [ftp://geoftp.ibge.gov.br/organizacao_do_territorio/tipologias_do_territorio/areas_urbanizadas_do_brasil](ftp://geoftp.ibge.gov.br/organizacao_do_territorio/tipologias_do_territorio/areas_urbanizadas_do_brasil)

**Comment by rafapereirabr** [comment]
done ! Thanks @babisan08

**Comment by rafapereirabr** [comment]
Oi Barbara. Acabei de reparar que nos dados de 2015 estao faltando os estados `"AP" "DF" "SE"`. Voce pode por favor checar o script `prep_` para ver o que aconteceu?

**Comment by babisan08** [comment]
done!
