### ISSUE TITLE
read_indigenous_land function not yet in package?

### ISSUE THREAD

**Issue by schmert** [ipeaGIT/geobr#54]
I have reinstalled from both CRAN and ipeaGIT/geobr on github, but in both cases the new _read_indigenous_land_ function doesn't seem available.

**Comment by rafapereirabr** [comment]
Hi Carl. This function is still only available in the development version. It worked for me with this code below. Let me know if this works for you as well.

```
devtools::install_github("ipeaGIT/geobr")
library(geobr)

packageVersion("geobr")
> ‘1.1’

i <- geobr::read_indigenous_land(date=201907)

```

**Comment by rafapereirabr** [comment]
it might be the case that you need to uninstall the package first ....
```
utils::remove.packages('geobr')
```
.... and then reinstall it again.
```
devtools::install_github("ipeaGIT/geobr")
```

**Comment by schmert** [comment]
With some additional package-related hiccups, the uninstall + reinstall eventually worked. Thanks. 

![TI](https://user-images.githubusercontent.com/6287005/65696400-23d56c00-e047-11e9-8b28-46f4e71e14cc.png)

**Comment by rafapereirabr** [comment]
:)

I'm glad to hear it worked, Carl. Closing this issue now.
