### ISSUE TITLE
New function to lookup codes

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#58]
1st, we need to create a `data.frame` with all names and codes of municipalities, micro regions, meso regions, states and regions. Something similar to the [fips_codes](https://github.com/walkerke/tigris/blob/master/R/fips_codes.R) [data ](https://github.com/walkerke/tigris/tree/master/data) in the tigris package. 

2nd, we need to create a function so that users can input either a state or municipality and get their respective code or name. The lookup_code function of tigris package can also be a great inspiration here. [See the code of their function starting at line 424 here](https://github.com/walkerke/tigris/blob/ad7d4e106c670df6e0a49390d8af7af760ceaa14/R/helpers.R).

**Comment by pedro-andrade-inpe** [comment]
It might be interesting to compute approximated results as well, if no exact match is found. One suggestion is to use Levenshtein distance with around 70 to 80% of match.

**Comment by rafapereirabr** [comment]
Following on Pedro's suggestion the `SoundexBR` [package facilitates finding matches of homophone strings in Portuguese](https://github.com/danielmarcelino/SoundexBR). This could be an option.

**Comment by rafapereirabr** [comment]
@kauebraga , favor ciar

- [ ] arquivo `prep_lookup` criando a base de referência (usar como base `read_municipality` e os codigos de micro, meso, immediate e intermediate

- [ ] função `lookup_code`
```
lookup_code <- fun(name_muni, code_muni){
  
return(df)
 > code_muni, name_muni, code_micro, name_micro, code_meso, code_immediate, code_intermediate, code_state, regiao
  
}
```

**Comment by kauebraga** [comment]
Function `lookup_muni` was created in https://github.com/ipeaGIT/geobr/commit/770ba1ad26f10bf973d6104fb5062a7eb11101b0 but I'll leave this issue open for futher discussions

**Comment by rafapereirabr** [comment]
Thanks ! I'll have a closer look at it latter this month

**Comment by rafapereirabr** [comment]
The function seems to be working fine! l'll close this issue for now.
