### ISSUE TITLE
New data: Environmental Conservation Units

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#60]

**Comment by cavedo95** [comment]
@rafapereirabr , por algum motivo eu continuo o com o mesmo erro, executei os dois comandos:
utils::remove.packages('geobr')
devtools::install_github("ipeaGIT/geobr") --> neste segundo comando é solicitado alguma das opções e selecionei 1. ALL após finalizar a instalação que termina com a mensagem * DONE (geobr). Executei o código read_biomes que está no git e encontrei o mesmo erro. (  Error: 'download_metadata' is not an exported object from 'namespace:geobr' ).

Contudo, eu consigo compilar os códigos antigos de read_biomes e em cima dele consegui fazer uma versão funcional de read_conservation_units.

[read_conservation_units.zip](https://github.com/ipeaGIT/geobr/files/3703812/read_conservation_units.zip)

**Comment by cavedo95** [comment]
@rafapereirabr consegui! Eram arquivos temporários mesmo o problema. Fiz uma versão do código já.

**Comment by rafapereirabr** [comment]
Ok. Eu tambem fiz umas correções noutros scripts q estavam gerando erro. Agora esta funcionando! Valeu.

**Comment by rafapereirabr** [comment]
Essa base de dados talvez interesse ao @pedro-andrade-inpe  ping
