### ISSUE TITLE
brand new biomes data

### ISSUE THREAD

**Issue by pedro-andrade-inpe** [ipeaGIT/geobr#72]
IBGE has just released the new biomes data, available at https://www.ibge.gov.br/apps/biomas/.

http://agenciabrasil.ebc.com.br/geral/noticia/2019-10/ibge-lanca-novo-mapa-com-biomas-brasileiros

**Comment by rafapereirabr** [comment]
Thanks for the heads up, Pedro. The new data set is at a much finer a spatial scale. I suggest we should simply replace the previous file with this one. I don't see strong reasons to keep both files but I'd be glad to have your thoughts on this

**Comment by pedro-andrade-inpe** [comment]
I believe we could keep both, as it is already there. There is always someone needing historical data, and it might not be easily available from IBGE's webpage anymore. It is also important to document it well, as someone not aweare of this change might think the data is wrong. I think it would also be nice to update the default year to 2019.
