### ISSUE TITLE
ggplot2 plotting speed

### ISSUE THREAD

**Issue by pedrovma** [ipeaGIT/geobr#76]
When using geobr in comparison with standard shp reading, I noticed a loss of speed in plotting with ggplot2. According to @rafapereirabr , this is probably due to the resolution of the shapefiles used in geobr. Hence I would suggest defaulting geobr to files with lower resolution to improve plotting speed.

**Comment by rafapereirabr** [comment]
We're currently working on this ;)

**Comment by rafapereirabr** [comment]
Pedro, the new dev version of geobr now has an additional argument `tp` as in data 'type'. It defaults to read data sets with 'simplified' borders, what makes the package much more efficient for downloading  and plotting the data.

**Comment by pedrovma** [comment]
Testing it next Monday! Super cool. Many thanks for this!

**Comment by rafapereirabr** [comment]
solved in v1.2
