### ISSUE TITLE
adicionar dados de Sede dos municipios

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#86]

**Comment by rafapereirabr** [comment]
data source: [link](ftp://geoftp.ibge.gov.br/organizacao_do_territorio/estrutura_territorial/localidades/)

**Comment by rafapereirabr** [comment]
Mais dados historicos das sedes: ftp://geoftp.ibge.gov.br/organizacao_do_territorio/estrutura_territorial/evolucao_da_divisao_territorial_do_brasil/evolucao_da_divisao_territorial_do_brasil_1872_2010/municipios_1872_1991/divisao_territorial_1872_1991/1950/

**Comment by rafapereirabr** [comment]
O nome da função vai ser `read_municipal_seat` :)

**Comment by rafapereirabr** [comment]
@babisan08 , consegui concertar o codigo. O script de prep agora faz download dos dados de 2010

**Comment by babisan08** [comment]
Sede dos municípios adicionada, só falta finalizar a documentação.

**Comment by rafapereirabr** [comment]
up and running!
