### ISSUE TITLE
multipla contagem de municipios em 2001 e 2005

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/geobr#89]
Eh comum alguns municipios terem descontinuidades no territorio (e.g. ilhas). Em 2001 e 2005, o shape de municipios do IBGE separa cada pedaco com uma observacao sepada.

Exemplo:
```
mun2001 <- read_municipality(year=2001, code_muni = 'RJ')
i2 <- subset(mun2001, name_muni== 'Itaguaí')

    code_muni name_muni code_state abbrev_state                       geometry
30    3302007   Itaguaí         33           RJ POLYGON ((-43.93858 -22.887...
146   3302007   Itaguaí         33           RJ POLYGON ((-43.88418 -22.947...
147   3302007   Itaguaí         33           RJ POLYGON ((-43.86587 -22.945...
148   3302007   Itaguaí         33           RJ POLYGON ((-43.86386 -22.955...
149   3302007   Itaguaí         33           RJ POLYGON ((-43.86462 -23.044...
150   3302007   Itaguaí         33           RJ POLYGON ((-43.70785 -22.987...

```

### correcao:
fazer group by no arquivo de prep

```
a2001_2 <-  a2001 %>% 
                          group_by(name_muni, name_metro, abbrev_state ) %>%
                                       summarise()
```

**Comment by babisan08** [comment]
1991 tambem erro

**Comment by rafapereirabr** [comment]
Oi @CaioNG . Parece que a correção não funcionou.  O exemplo de Itaguaí acima continua com o mesmo problema.

abs

**Comment by rafapereirabr** [comment]
Thanks @CaioNG !

**Comment by rafapereirabr** [comment]
Ah, reabrindo o issue. A @babisan08 lembrou que esse erro tambem ocorre na base de 1991. E parece que a solução que o @CaioNG funcionou para 2001 e 2005, mas 1991 continua com problema. Exemplo:

```
m <- read_municipality(year=1991)
i2 <- subset(m, code_muni== '2103703')
i2

# Quantas vezes cada municipios se repete
freq <- table(m$code_muni) %>% as.data.frame( )

# identifica repetidos
repetidos <- subset(freq, Freq >1 )


```

**Comment by rafapereirabr** [comment]
@ hi @CaioNG , are we not ready to close this issue yet, right? Could you have a look at this? The problem still persists for year 1991

**Comment by rafapereirabr** [comment]
@CaioNG , any updates on this?

**Comment by CaioNG** [comment]
I thought I had already corrected it, @PedroJorge7  also warned me of a problem that I thought I had solved the same day. I must have picked the wrong files. i will check and update you.

**Comment by CaioNG** [comment]
There was a problem in 2001 as well, it should be all fixed now.

**Comment by rafapereirabr** [comment]
Thanks!
